// This file is generated by src/extensions/tools/check-extension-model.mjs.
// Do not edit by hand.

/// Select the `amcheck` contrib extension.
pub const AMCHECK: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "amcheck",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `auto_explain` contrib extension.
pub const AUTO_EXPLAIN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "auto_explain",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `bloom` contrib extension.
pub const BLOOM: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "bloom",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `btree_gin` contrib extension.
pub const BTREE_GIN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "btree_gin",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `btree_gist` contrib extension.
pub const BTREE_GIST: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "btree_gist",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `citext` contrib extension.
pub const CITEXT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "citext",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `cube` contrib extension.
pub const CUBE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "cube",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `dict_int` contrib extension.
pub const DICT_INT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "dict_int",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `dict_xsyn` contrib extension.
pub const DICT_XSYN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "dict_xsyn",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `earthdistance` contrib extension.
pub const EARTHDISTANCE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "earthdistance",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `file_fdw` contrib extension.
pub const FILE_FDW: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "file_fdw",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `fuzzystrmatch` contrib extension.
pub const FUZZYSTRMATCH: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "fuzzystrmatch",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `hstore` contrib extension.
pub const HSTORE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "hstore",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `intarray` contrib extension.
pub const INTARRAY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "intarray",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `isn` contrib extension.
pub const ISN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "isn",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `lo` contrib extension.
pub const LO: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "lo",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `ltree` contrib extension.
pub const LTREE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "ltree",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pageinspect` contrib extension.
pub const PAGEINSPECT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pageinspect",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_buffercache` contrib extension.
pub const PG_BUFFERCACHE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_buffercache",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_freespacemap` contrib extension.
pub const PG_FREESPACEMAP: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_freespacemap",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_surgery` contrib extension.
pub const PG_SURGERY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_surgery",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_trgm` contrib extension.
pub const PG_TRGM: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_trgm",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_visibility` contrib extension.
pub const PG_VISIBILITY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_visibility",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pg_walinspect` contrib extension.
pub const PG_WALINSPECT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_walinspect",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `pgcrypto` contrib extension.
pub const PGCRYPTO: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pgcrypto",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `seg` contrib extension.
pub const SEG: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "seg",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `tablefunc` contrib extension.
pub const TABLEFUNC: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tablefunc",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `tcn` contrib extension.
pub const TCN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tcn",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `tsm_system_rows` contrib extension.
pub const TSM_SYSTEM_ROWS: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tsm_system_rows",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `tsm_system_time` contrib extension.
pub const TSM_SYSTEM_TIME: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tsm_system_time",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `unaccent` contrib extension.
pub const UNACCENT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "unaccent",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};

/// Select the `uuid-ossp` contrib extension.
pub const UUID_OSSP: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "uuid-ossp",
    product: "oliphaunt-extension-contrib-pg18",
    version: None,
    runtime_version: env!("OLIPHAUNT_NATIVE_RUNTIME_VERSION"),
    resources: &[],
};
