name = "pg_textsearch"
url = "https://github.com/timescale/pg_textsearch.git"
branch = "pinned"
commit = "578ff529894992fb9e67cae4c69424e65c84868e"

[extension-control]
sql-name = "pg_textsearch"
source-path = "pg_textsearch.control"
default-version = "1.3.1"
