[package]
name = "oliphaunt-wasix-tools"
version = "0.1.1"
edition = "2024"
rust-version = "1.93"
description = "WASIX pg_dump and psql assets for oliphaunt-wasix"
repository = "https://github.com/f0rr0/oliphaunt"
homepage = "https://oliphaunt.dev"
documentation = "https://docs.rs/oliphaunt-wasix-tools"
license = "MIT AND PostgreSQL AND Unicode-3.0"
publish = false
links = "oliphaunt_artifact_oliphaunt_wasix_tools"
include = [
  "Cargo.toml",
  "build.rs",
  "README.md",
  "src/**",
  "payload/**",
  "LICENSE",
  "THIRD_PARTY_NOTICES.md",
  "THIRD_PARTY_NOTICES.oliphaunt-wasix.md",
  "THIRD_PARTY_LICENSES/PostgreSQL-COPYRIGHT",
  "THIRD_PARTY_LICENSES/ICU-LICENSE",
]

[package.metadata.oliphaunt-wasix-tools.assets]
pg-dump-wasix-sha256 = "90180532a2d4ccd68405f9ecc3057607e84fb5a033ae51541bc36535a8311909"
psql-wasix-sha256 = "894aeb0d846c249e4697a4795184b2e6a470ca53daa4819f61c204f05baf9c8d"

[lib]
path = "src/lib.rs"

[build-dependencies]
sha2 = "0.10"
