[package]
name = "oliphaunt-wasix-tools"
version = "0.1.1"
edition = "2024"
rust-version = "1.93"
description = "WASIX pg_dump and psql assets for oliphaunt-wasix"
repository = "https://github.com/f0rr0/oliphaunt"
homepage = "https://oliphaunt.dev"
documentation = "https://docs.rs/oliphaunt-wasix-tools"
license = "MIT AND PostgreSQL AND Unicode-3.0"
publish = false
links = "oliphaunt_artifact_oliphaunt_wasix_tools"
include = [
  "Cargo.toml",
  "build.rs",
  "README.md",
  "src/**",
  "payload/**",
  "LICENSE",
  "THIRD_PARTY_NOTICES.md",
  "THIRD_PARTY_NOTICES.oliphaunt-wasix.md",
  "THIRD_PARTY_LICENSES/PostgreSQL-COPYRIGHT",
  "THIRD_PARTY_LICENSES/ICU-LICENSE",
]

[package.metadata.oliphaunt-wasix-tools.assets]
pg-dump-wasix-sha256 = "6f6356b43bf75402a209c48fec8c415098788b63a37ed77464ce06c45e2491ad"
psql-wasix-sha256 = "f1cb7bbcce420dd97619dc4e18be954b6605f5b643119a5d90809d14db7a0451"

[lib]
path = "src/lib.rs"

[build-dependencies]
sha2 = "0.10"
