[workspace]
members = [
  "sdks/ts/node-addon",
  "sdks/rust/liboliphaunt-native",
  "sdks/rust/mobile-bindings",
  "sdks/rust-query",
  "sdks/rust-wasix",
  "sdks/rust/sdk/crates/oliphaunt-build",
  "sdks/rust/sdk",
  "postgres-tools/native/crates/tools",
  "broker",
  "pgwire-server",
  "database-resources/icu/cargo",
  "database-resources/seeds/wasix",
  "runtimes/liboliphaunt-wasix/crates/assets",
  "postgres-tools/wasix/crates/tools",
  "runtimes/liboliphaunt-wasix/crates/aot/aarch64-apple-darwin",
  "runtimes/liboliphaunt-wasix/crates/aot/x86_64-unknown-linux-gnu",
  "runtimes/liboliphaunt-wasix/crates/aot/aarch64-unknown-linux-gnu",
  "runtimes/liboliphaunt-wasix/crates/aot/x86_64-pc-windows-msvc",
  "postgres-tools/wasix/crates/aot/aarch64-apple-darwin",
  "postgres-tools/wasix/crates/aot/x86_64-unknown-linux-gnu",
  "postgres-tools/wasix/crates/aot/aarch64-unknown-linux-gnu",
  "postgres-tools/wasix/crates/aot/x86_64-pc-windows-msvc",
  "sdks/ts-wasix/node-addon",
  "benchmarks/perf/runner",
  "extensions/tests/native",
  "runtimes/liboliphaunt-native/packaging",
  "postgres-tools/native/tests",
  "runtimes/liboliphaunt-wasix/tools/xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.93"
repository = "https://github.com/f0rr0/oliphaunt"
homepage = "https://oliphaunt.dev"
license = "MIT"

[profile.release]
strip = "symbols"
