// swift-tools-version: 6.0

import PackageDescription

// Generated by src/native/sdks/swift/tools/render_swiftpm_release_package.mts.
// This is the public SwiftPM release manifest. The source package under
// src/native/sdks/swift remains the local development package.
// Exact PostgreSQL extensions are released as separate opt-in extension
// artifacts. The base Swift package must not require or publish extension files.
let package = Package(
    name: "Oliphaunt",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)
    ],
    products: [
        .library(name: "COliphaunt", targets: ["COliphaunt"]),
        .library(name: "Oliphaunt", targets: ["Oliphaunt"]),
        .library(name: "OliphauntCore", targets: ["OliphauntCore"]),
        .library(name: "OliphauntBroker", targets: ["OliphauntBroker"]),
        .library(name: "OliphauntBrokerExtension", targets: ["OliphauntBrokerExtension"]),
        .library(name: "OliphauntExtensionSupport", targets: ["OliphauntExtensionSupport"])
    ],
    targets: [
        .binaryTarget(
            name: "OliphauntNativeBindingsFFI",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/oliphaunt-swift-v0.8.2/oliphaunt-swift-0.8.2-bindings.xcframework.zip",
            checksum: "118c2fc8634e2e6d652797b279f45a693cbe2a5be314fb40760c02204d844441"
        ),
        .target(
            name: "OliphauntNativeBindings",
            dependencies: ["OliphauntNativeBindingsFFI"],
            path: "src/sdks/swift/Sources/OliphauntNativeBindings"
        ),
        .binaryTarget(
            name: "liboliphaunt",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/liboliphaunt-native-v0.3.3/liboliphaunt-0.3.3-apple-spm-xcframework.zip",
            checksum: "e6311658046cb2714bc0c1a7c5610f6ce36cda2156c8092aea21500cce7f2ba1"
        ),
        .target(
            name: "COliphaunt",
            dependencies: ["liboliphaunt"],
            path: "src/sdks/swift/Sources/COliphaunt",
            publicHeadersPath: "include",
            cSettings: [.define("OLIPHAUNT_LINK_RUNTIME")]
        ),
        .target(
            name: "OliphauntCore",
            dependencies: ["OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntCore"
        ),
        .target(
            name: "OliphauntBroker",
            dependencies: ["OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBroker"
        ),
        .target(
            name: "OliphauntBrokerExtension",
            dependencies: ["Oliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBrokerExtension"
        ),
        .target(
            name: "Oliphaunt",
            dependencies: ["COliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/Oliphaunt"
        ),
        .target(
            name: "OliphauntExtensionSupport",
            dependencies: ["COliphaunt", "Oliphaunt"],
            path: "src/sdks/swift/Sources/OliphauntExtensionSupport"
        )
    ]
)
