// swift-tools-version: 6.0

import PackageDescription

// Generated by src/native/sdks/swift/tools/render_swiftpm_release_package.mts.
// This is the public SwiftPM release manifest. The source package under
// src/native/sdks/swift remains the local development package.
// Exact PostgreSQL extensions are released as separate opt-in extension
// artifacts. The base Swift package must not require or publish extension files.
let package = Package(
    name: "Oliphaunt",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)
    ],
    products: [
        .library(name: "COliphaunt", targets: ["COliphaunt"]),
        .library(name: "Oliphaunt", targets: ["Oliphaunt"]),
        .library(name: "OliphauntCore", targets: ["OliphauntCore"]),
        .library(name: "OliphauntBroker", targets: ["OliphauntBroker"]),
        .library(name: "OliphauntBrokerExtension", targets: ["OliphauntBrokerExtension"]),
        .library(name: "OliphauntExtensionSupport", targets: ["OliphauntExtensionSupport"])
    ],
    targets: [
        .binaryTarget(
            name: "OliphauntNativeBindingsFFI",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/oliphaunt-swift-v0.8.1/oliphaunt-swift-0.8.1-bindings.xcframework.zip",
            checksum: "9c85cf78b9363ea8b6552d115f7f3323f8e5f22309ad080b5ec9399034d6118e"
        ),
        .target(
            name: "OliphauntNativeBindings",
            dependencies: ["OliphauntNativeBindingsFFI"],
            path: "src/sdks/swift/Sources/OliphauntNativeBindings"
        ),
        .binaryTarget(
            name: "liboliphaunt",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/liboliphaunt-native-v0.3.2/liboliphaunt-0.3.2-apple-spm-xcframework.zip",
            checksum: "915ea189f2ad74ac31fc4402dc31f00d4f42c4dcfe73e360db7cd0f36419dec8"
        ),
        .target(
            name: "COliphaunt",
            dependencies: ["liboliphaunt"],
            path: "src/sdks/swift/Sources/COliphaunt",
            publicHeadersPath: "include",
            cSettings: [.define("OLIPHAUNT_LINK_RUNTIME")]
        ),
        .target(
            name: "OliphauntCore",
            dependencies: ["OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntCore"
        ),
        .target(
            name: "OliphauntBroker",
            dependencies: ["OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBroker"
        ),
        .target(
            name: "OliphauntBrokerExtension",
            dependencies: ["Oliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBrokerExtension"
        ),
        .target(
            name: "Oliphaunt",
            dependencies: ["COliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/Oliphaunt"
        ),
        .target(
            name: "OliphauntExtensionSupport",
            dependencies: ["COliphaunt", "Oliphaunt"],
            path: "src/sdks/swift/Sources/OliphauntExtensionSupport"
        )
    ]
)
