// swift-tools-version: 6.0

import PackageDescription

// Generated by src/native/sdks/swift/tools/render_swiftpm_release_package.mts.
// This is the public SwiftPM release manifest. The source package under
// src/native/sdks/swift remains the local development package.
// Exact PostgreSQL extensions are released as separate opt-in extension
// artifacts. The base Swift package must not require or publish extension files.
let package = Package(
    name: "Oliphaunt",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)
    ],
    products: [
        .library(name: "COliphaunt", targets: ["COliphaunt"]),
        .library(name: "Oliphaunt", targets: ["Oliphaunt"]),
        .library(name: "OliphauntCore", targets: ["OliphauntCore"]),
        .library(name: "OliphauntBroker", targets: ["OliphauntBroker"]),
        .library(name: "OliphauntBrokerExtension", targets: ["OliphauntBrokerExtension"]),
        .library(name: "OliphauntExtensionSupport", targets: ["OliphauntExtensionSupport"])
    ],
    targets: [
        .binaryTarget(
            name: "OliphauntNativeBindingsFFI",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/oliphaunt-swift-v0.8.0/oliphaunt-swift-0.8.0-bindings.xcframework.zip",
            checksum: "2fdd77e750e69116f461767a48976f2b241f1282ab632028d80d9033c9cf9bef"
        ),
        .target(
            name: "OliphauntNativeBindings",
            dependencies: ["OliphauntNativeBindingsFFI"],
            path: "src/sdks/swift/Sources/OliphauntNativeBindings"
        ),
        .binaryTarget(
            name: "liboliphaunt",
            url: "https://github.com/f0rr0/oliphaunt/releases/download/liboliphaunt-native-v0.3.0/liboliphaunt-0.3.0-apple-spm-xcframework.zip",
            checksum: "7d3ea7edea97d48b2795e8fb5db26b6fd5f7f214fd3230f4265e3b54546cfee5"
        ),
        .target(
            name: "COliphaunt",
            dependencies: ["liboliphaunt"],
            path: "src/sdks/swift/Sources/COliphaunt",
            publicHeadersPath: "include",
            cSettings: [.define("OLIPHAUNT_LINK_RUNTIME")]
        ),
        .target(
            name: "OliphauntCore",
            dependencies: ["OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntCore"
        ),
        .target(
            name: "OliphauntBroker",
            dependencies: ["OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBroker"
        ),
        .target(
            name: "OliphauntBrokerExtension",
            dependencies: ["Oliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/OliphauntBrokerExtension"
        ),
        .target(
            name: "Oliphaunt",
            dependencies: ["COliphaunt", "OliphauntCore", "OliphauntNativeBindings"],
            path: "src/sdks/swift/Sources/Oliphaunt"
        ),
        .target(
            name: "OliphauntExtensionSupport",
            dependencies: ["COliphaunt", "Oliphaunt"],
            path: "src/sdks/swift/Sources/OliphauntExtensionSupport"
        )
    ]
)
