// Generated by src/wasix/runtime/protocol-contract/generate.mjs.
// Staged as src/protocol_contract.rs in the patched Wasmer JS host.
pub(crate) const PROTOCOL_CALLBACK_CHUNK_BYTES: usize = 65536;
pub(crate) const PROTOCOL_BUFFERED: i32 = 0;
pub(crate) const PROTOCOL_HYBRID: i32 = 2;
pub(crate) const PROTOCOL_BUFFERED_INPUT_STREAMED_OUTPUT: i32 = 3;
