// This file is generated by src/extensions/tools/check-extension-model.sh.
// Do not edit by hand.

import {
  GENERATED_EXTENSION_METADATA,
  generatedExtensionBySqlName,
} from './generated/extensions.js';

/** A selected native extension. External packages export their own descriptors. */
export type NativeExtension = {
  readonly schema: 'oliphaunt-native-extension-v1';
  readonly sqlName: string;
  readonly product: string;
  readonly packageName: string;
  readonly version?: string;
  /** Present in the Node/Bun/Deno export; mobile resolves linked resources. */
  readonly packageJsonUrl?: string;
};

type ExtensionId = Extract<
  (typeof GENERATED_EXTENSION_METADATA)[number],
  { readonly runtimeBound: true }
>['id'];

/** Selecting an extension makes its files available; it does not execute SQL. */
export const extensions = Object.freeze(
  Object.fromEntries(
    GENERATED_EXTENSION_METADATA.filter((row) => row.runtimeBound).map((row) => [
      row.id,
      Object.freeze({
        schema: 'oliphaunt-native-extension-v1' as const,
        sqlName: row.sqlName,
        product: row.artifactProduct,
        packageName: row.npmPackage,
      }),
    ]),
  ),
) as Readonly<Record<ExtensionId, NativeExtension>>;

/** @internal Validate and snapshot descriptors before asynchronous work. */
export function normalizeExtensions(values: readonly NativeExtension[] = []): NativeExtension[] {
  const selected = new Map<string, NativeExtension>();
  for (const value of values) {
    const metadata = generatedExtensionBySqlName(value?.sqlName);
    if (
      value?.schema !== 'oliphaunt-native-extension-v1' ||
      metadata === undefined ||
      value.product !== metadata.artifactProduct ||
      value.packageName !== metadata.npmPackage ||
      (!metadata.runtimeBound && (typeof value.version !== 'string' || value.version.length === 0))
    ) {
      throw new Error(
        'extensions must contain native extension descriptors imported from their packages',
      );
    }
    if (value.packageJsonUrl !== undefined && typeof value.packageJsonUrl !== 'string') {
      throw new Error('extension packageJsonUrl must be a string');
    }
    const snapshot: NativeExtension = Object.freeze({
      schema: value.schema,
      sqlName: value.sqlName,
      product: value.product,
      packageName: value.packageName,
      ...(value.version !== undefined ? { version: value.version } : {}),
      ...(value.packageJsonUrl !== undefined ? { packageJsonUrl: value.packageJsonUrl } : {}),
    });
    const previous = selected.get(value.sqlName);
    if (
      previous !== undefined &&
      (previous.version !== snapshot.version || previous.packageJsonUrl !== snapshot.packageJsonUrl)
    ) {
      throw new Error('conflicting selected extension packages for ' + value.sqlName);
    }
    selected.set(value.sqlName, snapshot);
  }
  for (const value of selected.values()) {
    for (const sqlName of generatedExtensionBySqlName(value.sqlName)!
      .selectedExtensionDependencies) {
      const dependency = generatedExtensionBySqlName(sqlName)!;
      const existing = selected.get(sqlName);
      if (existing !== undefined) {
        if (
          dependency.artifactProduct === value.product &&
          (existing.version !== value.version || existing.packageJsonUrl !== value.packageJsonUrl)
        ) {
          throw new Error('conflicting selected extension packages for ' + sqlName);
        }
        continue;
      }
      if (dependency.artifactProduct !== value.product && !dependency.runtimeBound) {
        throw new Error('select the external extension dependency explicitly: ' + sqlName);
      }
      selected.set(
        sqlName,
        Object.freeze(
          dependency.artifactProduct === value.product
            ? { ...value, sqlName }
            : {
                schema: value.schema,
                sqlName,
                product: dependency.artifactProduct,
                packageName: dependency.npmPackage,
              },
        ),
      );
    }
  }
  return [...selected.values()];
}
