import { describe, expect, test } from 'bun:test';

import {
  mergeMobileStaticSpecRegistries,
  selectMobileStaticModuleSqlNames,
} from '../../src/extensions/artifacts/native/tools/extension-artifact-packager.mjs';

const HEADER = [
  'sql-name',
  'native-module-stem',
  'source-kind',
  'source-rel',
  'mobile-static-dependencies',
  'ios-static-dependencies',
  'android-static-dependencies',
  'include-dependencies',
  'include-dirs',
  'cflags',
  'hash-source-dependencies',
  'ios-hash-source-dependencies',
  'android-hash-source-dependencies',
  'hash-dirs',
  'source-files',
  'source-recursive-dirs',
].join('\t');

function specRow(sqlName, stem = sqlName) {
  return [sqlName, stem, 'external', `checkouts/${sqlName}`, ...Array(12).fill('')].join('\t');
}

function specTable(rows) {
  return [`# @generated by test`, HEADER, ...rows, ''].join('\n');
}

describe('mixed public and qualification mobile extension selection', () => {
  test('SQL-only qualification candidates do not enter static module builds', () => {
    const rows = [
      {
        sqlName: 'amcheck',
        stem: 'amcheck',
        mobilePrebuilt: true,
        mobileStaticRequired: true,
      },
      {
        sqlName: 'pgmq',
        stem: '',
        mobilePrebuilt: true,
        mobileStaticRequired: false,
      },
    ];

    expect(selectMobileStaticModuleSqlNames(rows, ['amcheck', 'pgmq'])).toEqual(['amcheck']);
  });

  test('public and qualification static registries remain available together', () => {
    const merged = mergeMobileStaticSpecRegistries(
      specTable([specRow('amcheck')]),
      specTable([specRow('candidate_module')]),
    );

    expect(merged).toContain(specRow('amcheck'));
    expect(merged).toContain(specRow('candidate_module'));
    expect(merged.indexOf(specRow('amcheck'))).toBeLessThan(merged.indexOf(specRow('candidate_module')));
  });

  test('qualification registries cannot shadow public extension specs', () => {
    expect(() => mergeMobileStaticSpecRegistries(
      specTable([specRow('amcheck')]),
      specTable([specRow('amcheck')]),
    )).toThrow("overlaps public SQL name 'amcheck'");
  });
});
