import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import path from "node:path";

const publisher = readFileSync(path.join(import.meta.dir, "release-publish.mjs"), "utf8");
const npmPublisher = readFileSync(path.join(import.meta.dir, "frozen-npm-publish.mjs"), "utf8");

function frozenPublishContract(source, npmSource = npmPublisher) {
  return source.includes("cratePath: locked.file")
    && source.includes("tarball: locked.file")
    && npmSource.includes('["publish", file, "--access", "public", "--provenance", "--registry", canonicalRegistry]')
    && npmSource.includes("const expectedIntegrity = frozenNpmIntegrity(file)")
    && source.includes("prepareFrozenMavenBundle({")
    && source.includes("deadlineEpochSeconds: registryMutationDeadlineSeconds()")
    && source.includes("lockedProductArtifactPaths(ACTIVE_PUBLICATION_LOCK, product)")
    && source.includes('"--publication-lock",\n    PUBLICATION_LOCK_PATH,')
    && source.includes("lockedCarrierDirectory(ACTIVE_PUBLICATION_LOCK, \"jsr\"")
    && source.includes("await publishBootstrapCarrier(")
    && source.includes("await cargoPublishLockedCrate(carrier.name, carrier.version, locked.file)")
    && source.includes("npmPublishTarball(carrier.name, locked.file, carrier.version)")
    && source.includes("identityCreationOnly: BOOTSTRAP_IDENTITIES")
    && source.includes("identity bootstrap cannot publish ${crateName} ${version}")
    && source.includes("exactVersionPublished: () => exactCargoVersionPublished(crateName, version, {")
    && source.includes("identityCreationOnly: false,")
    && source.includes("normalPublicationPlan(ACTIVE_PUBLICATION_LOCK, products)")
    && source.includes("executeNormalPublicationPlan({")
    && source.includes("normal Maven operation does not contain every selected frozen Maven carrier")
    && source.includes("pendingProducts.length !== operation.products.length")
    && source.includes("verifyLockedCarrierIntegrity(ACTIVE_PUBLICATION_LOCK, `cargo:${crateName}`)")
    && source.includes("await boundedRegistrySleep(10_000")
    && source.includes("requirePreMutationRegistryWindow({")
    && source.includes("minimumMilliseconds: NORMAL_REGISTRY_MAVEN_OPERATION_SECONDS * 1000")
    && source.includes("minimumMilliseconds: NORMAL_REGISTRY_JSR_SECONDS_PER_CARRIER * 1000")
    && source.includes("timeout,")
    && source.includes("normal product/ecosystem registry steps are disabled; use the exact-lock --registry-plan executor")
    && !source.includes('"cargo", "publish"')
    && !source.includes('spawnSync("npm", ["view"')
    && !source.includes("package_broker_cargo_artifacts.mjs")
    && !source.includes("package-liboliphaunt-cargo-artifacts.mjs")
    && !source.includes("package_liboliphaunt_wasix_cargo_artifacts.mjs")
    && !source.includes("stageExtensionNpmPackages(");
}

describe("real publication consumes frozen artifacts", () => {
  test("contains no registry rebuild route", () => {
    expect(frozenPublishContract(publisher)).toBe(true);
  });

  test("semantic mutations that substitute regenerated bytes violate the contract", () => {
    expect(frozenPublishContract(publisher.replace("cratePath: locked.file", "cratePath: regenerated.file"))).toBe(false);
    expect(frozenPublishContract(publisher.replace("tarball: locked.file", "tarball: regenerated.file"))).toBe(false);
    expect(frozenPublishContract(publisher, npmPublisher.replace('["publish", file', '["publish", regenerated'))).toBe(false);
    expect(frozenPublishContract(publisher.replace("prepareFrozenMavenBundle({", "runMavenArtifactPublisher("))).toBe(false);
    expect(frozenPublishContract(publisher.replace('"--publication-lock",\n    PUBLICATION_LOCK_PATH,', '"--publication-lock",\n    DEFAULT_PUBLICATION_LOCK,'))).toBe(false);
    expect(frozenPublishContract(publisher.replaceAll("deadlineEpochSeconds: registryMutationDeadlineSeconds()", "deadlineEpochSeconds: undefined"))).toBe(false);
    expect(frozenPublishContract(publisher.replaceAll("await boundedRegistrySleep(10_000", "await Bun.sleep(10_000"))).toBe(false);
    expect(frozenPublishContract(publisher.replace(
      "minimumMilliseconds: NORMAL_REGISTRY_MAVEN_OPERATION_SECONDS * 1000",
      "minimumMilliseconds: 1",
    ))).toBe(false);
    expect(frozenPublishContract(publisher.replace(
      "minimumMilliseconds: NORMAL_REGISTRY_JSR_SECONDS_PER_CARRIER * 1000",
      "minimumMilliseconds: 1",
    ))).toBe(false);
    expect(frozenPublishContract(publisher.replace("identityCreationOnly: false,", "identityCreationOnly,"))).toBe(false);
    expect(frozenPublishContract(publisher.replace("timeout,", "timeout: undefined,"))).toBe(false);
    expect(frozenPublishContract(publisher.replace("normalPublicationPlan(ACTIVE_PUBLICATION_LOCK, products)", "manualRegistryPlan(products)"))).toBe(false);
    expect(frozenPublishContract(publisher.replace("pendingProducts.length !== operation.products.length", "false"))).toBe(false);
    expect(frozenPublishContract(`${publisher}\nconst mutation = ["cargo", "publish"];`)).toBe(false);
  });

  test("treats a selected source-only release as a valid empty registry plan", () => {
    const start = publisher.indexOf("if (plan.carrierCount === 0)");
    const emptyPlan = publisher.slice(start, publisher.indexOf("requireNormalRegistryProductInputs(products)", start));
    expect(emptyPlan).toContain("writeRegistryReceiptEvidence");
    expect(emptyPlan).toContain('ecosystems: ["cargo", "npm", "maven", "jsr"]');
    expect(emptyPlan).toContain("receipts: []");
    expect(emptyPlan).toContain("return;");
    expect(emptyPlan).toContain("loadBoundNormalPublicationAdmission");
    expect(emptyPlan).toContain("empty registry topology received a nonempty normal-publication admission partition");
  });

  test("reuses bootstrap receipts and preserves publisher-returned exact receipts without a full verification replay", () => {
    expect(publisher).toContain("loadBootstrapLedger(BOOTSTRAP_LEDGER_PATH");
    expect(publisher).toContain("requireComplete: true");
    expect(publisher).toContain("if (provenReceipts.has(operation.carrierId)) return true");
    expect(publisher).toContain("covered by the complete immutable bootstrap ledger; skipping redundant registry reconciliation");
    expect(publisher).toContain("const execution = await executeNormalPublicationPlan");
    expect(publisher).toContain("operationResults: execution.operationResults");
    expect(publisher).toContain("collectNormalPublicationReceipts({");
    expect(publisher).toContain("verifyLockedRegistryIntegrity(ACTIVE_PUBLICATION_LOCK");
    expect(publisher).toContain("writeRegistryReceiptEvidence(REGISTRY_RECEIPT_EVIDENCE_PATH");
    expect(publisher).not.toContain("const remainingCarrierIds");
  });

  test("the unified asset handoff uses one bounded exact selected-tag snapshot", () => {
    const handoff = publisher.slice(
      publisher.indexOf("async function publishSelectedGithubReleaseAssetSets"),
      publisher.indexOf("function selectedExtensionProducts"),
    );
    expect(handoff).toContain("readSelectedRemoteTagMapSync(repo, selectedTags");
    expect(handoff).toContain("remote?.type !== \"commit\" || remote.sha !== headRef");
    expect(handoff).not.toContain("verifyReleaseTag(product, headRef)");
  });

  test("keeps every command failure inside concurrent normal registry lanes throwable", () => {
    const jsr = publisher.slice(
      publisher.indexOf("async function publishTypescriptJsr"),
      publisher.indexOf("async function publishRustCratesIo"),
    );
    const maven = publisher.slice(
      publisher.indexOf("async function publishNormalMavenOperation"),
      publisher.indexOf("async function publishNormalCarrier"),
    );
    const carrier = publisher.slice(
      publisher.indexOf("async function publishNormalCarrier"),
      publisher.indexOf("function requireNormalRegistryProductInputs"),
    );
    expect(jsr).toContain("runOrThrow(TOOL");
    expect(jsr).toContain("mutateOnceAndRequireExactState");
    expect(jsr).toContain("JSR_PUBLISH_TIMEOUT_MS");
    expect(jsr).toContain("requireProductRegistryPublishedOrThrow");
    expect(jsr.match(/resolvePinnedJsrInvocation\(\["publish"\]\)/gu)?.length).toBe(1);
    expect(jsr).not.toContain('["pnpm", "exec", "jsr"');
    expect(jsr).toContain("reconciledMutationFailure");
    expect(jsr).not.toContain("run(TOOL");
    expect(jsr).not.toContain("fail(");
    expect(maven).toContain("verifyReleaseTagOrThrow");
    expect(maven).toContain("requireProductRegistryPublishedOrThrow");
    expect(maven).not.toContain("run(TOOL");
    expect(maven).not.toContain("fail(");
    expect(carrier).not.toContain("process.exit");
    expect(carrier).not.toContain("fail(");
  });
});
