import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import path from "node:path";

const publisher = readFileSync(path.join(import.meta.dir, "release-publish.mjs"), "utf8");

function frozenPublishContract(source) {
  return source.includes("cratePath: locked.file")
    && source.includes('["npm", "publish", locked.file')
    && source.includes("prepareFrozenMavenBundle({")
    && source.includes("lockedProductArtifactPaths(ACTIVE_PUBLICATION_LOCK, product)")
    && source.includes("lockedCarrierDirectory(ACTIVE_PUBLICATION_LOCK, \"jsr\"")
    && source.includes("await publishBootstrapCarrier(")
    && source.includes("await cargoPublishLockedCrate(carrier.name, carrier.version, locked.file)")
    && source.includes("npmPublishTarball(carrier.name, locked.file, carrier.version)")
    && source.includes("normalPublicationPlan(ACTIVE_PUBLICATION_LOCK, products)")
    && source.includes("executeNormalPublicationPlan({")
    && source.includes("normal Maven operation does not contain every selected frozen Maven carrier")
    && source.includes("pendingProducts.length !== operation.products.length")
    && source.includes("verifyLockedCarrierIntegrity(ACTIVE_PUBLICATION_LOCK, `cargo:${crateName}`)")
    && source.includes("normal product/ecosystem registry steps are disabled; use the exact-lock --registry-plan executor")
    && !source.includes('"cargo", "publish"')
    && !source.includes("package_broker_cargo_artifacts.mjs")
    && !source.includes("package-liboliphaunt-cargo-artifacts.mjs")
    && !source.includes("package_liboliphaunt_wasix_cargo_artifacts.mjs")
    && !source.includes("stageExtensionNpmPackages(");
}

describe("real publication consumes frozen artifacts", () => {
  test("contains no registry rebuild route", () => {
    expect(frozenPublishContract(publisher)).toBe(true);
  });

  test("semantic mutations that substitute regenerated bytes violate the contract", () => {
    expect(frozenPublishContract(publisher.replace("cratePath: locked.file", "cratePath: regenerated.file"))).toBe(false);
    expect(frozenPublishContract(publisher.replace('["npm", "publish", locked.file', '["npm", "publish", tarball'))).toBe(false);
    expect(frozenPublishContract(publisher.replace("prepareFrozenMavenBundle({", "runMavenArtifactPublisher("))).toBe(false);
    expect(frozenPublishContract(publisher.replace("normalPublicationPlan(ACTIVE_PUBLICATION_LOCK, products)", "manualRegistryPlan(products)"))).toBe(false);
    expect(frozenPublishContract(publisher.replace("pendingProducts.length !== operation.products.length", "false"))).toBe(false);
    expect(frozenPublishContract(`${publisher}\nconst mutation = ["cargo", "publish"];`)).toBe(false);
  });
});
