// This file is generated by src/extensions/tools/check-extension-model.mjs.
// Do not edit by hand.

public enum OliphauntExtensions {
    public static let amcheck = OliphauntExtension(sqlName: "amcheck", product: "oliphaunt-extension-contrib-pg18")
    public static let autoExplain = OliphauntExtension(sqlName: "auto_explain", product: "oliphaunt-extension-contrib-pg18")
    public static let bloom = OliphauntExtension(sqlName: "bloom", product: "oliphaunt-extension-contrib-pg18")
    public static let btreeGin = OliphauntExtension(sqlName: "btree_gin", product: "oliphaunt-extension-contrib-pg18")
    public static let btreeGist = OliphauntExtension(sqlName: "btree_gist", product: "oliphaunt-extension-contrib-pg18")
    public static let citext = OliphauntExtension(sqlName: "citext", product: "oliphaunt-extension-contrib-pg18")
    public static let cube = OliphauntExtension(sqlName: "cube", product: "oliphaunt-extension-contrib-pg18")
    public static let dictInt = OliphauntExtension(sqlName: "dict_int", product: "oliphaunt-extension-contrib-pg18")
    public static let dictXsyn = OliphauntExtension(sqlName: "dict_xsyn", product: "oliphaunt-extension-contrib-pg18")
    public static let earthdistance = OliphauntExtension(sqlName: "earthdistance", product: "oliphaunt-extension-contrib-pg18")
    public static let fileFdw = OliphauntExtension(sqlName: "file_fdw", product: "oliphaunt-extension-contrib-pg18")
    public static let fuzzystrmatch = OliphauntExtension(sqlName: "fuzzystrmatch", product: "oliphaunt-extension-contrib-pg18")
    public static let hstore = OliphauntExtension(sqlName: "hstore", product: "oliphaunt-extension-contrib-pg18")
    public static let intarray = OliphauntExtension(sqlName: "intarray", product: "oliphaunt-extension-contrib-pg18")
    public static let isn = OliphauntExtension(sqlName: "isn", product: "oliphaunt-extension-contrib-pg18")
    public static let lo = OliphauntExtension(sqlName: "lo", product: "oliphaunt-extension-contrib-pg18")
    public static let ltree = OliphauntExtension(sqlName: "ltree", product: "oliphaunt-extension-contrib-pg18")
    public static let pageinspect = OliphauntExtension(sqlName: "pageinspect", product: "oliphaunt-extension-contrib-pg18")
    public static let pgBuffercache = OliphauntExtension(sqlName: "pg_buffercache", product: "oliphaunt-extension-contrib-pg18")
    public static let pgFreespacemap = OliphauntExtension(sqlName: "pg_freespacemap", product: "oliphaunt-extension-contrib-pg18")
    public static let pgSurgery = OliphauntExtension(sqlName: "pg_surgery", product: "oliphaunt-extension-contrib-pg18")
    public static let pgTrgm = OliphauntExtension(sqlName: "pg_trgm", product: "oliphaunt-extension-contrib-pg18")
    public static let pgVisibility = OliphauntExtension(sqlName: "pg_visibility", product: "oliphaunt-extension-contrib-pg18")
    public static let pgWalinspect = OliphauntExtension(sqlName: "pg_walinspect", product: "oliphaunt-extension-contrib-pg18")
    public static let pgcrypto = OliphauntExtension(sqlName: "pgcrypto", product: "oliphaunt-extension-contrib-pg18")
    public static let seg = OliphauntExtension(sqlName: "seg", product: "oliphaunt-extension-contrib-pg18")
    public static let tablefunc = OliphauntExtension(sqlName: "tablefunc", product: "oliphaunt-extension-contrib-pg18")
    public static let tcn = OliphauntExtension(sqlName: "tcn", product: "oliphaunt-extension-contrib-pg18")
    public static let tsmSystemRows = OliphauntExtension(sqlName: "tsm_system_rows", product: "oliphaunt-extension-contrib-pg18")
    public static let tsmSystemTime = OliphauntExtension(sqlName: "tsm_system_time", product: "oliphaunt-extension-contrib-pg18")
    public static let unaccent = OliphauntExtension(sqlName: "unaccent", product: "oliphaunt-extension-contrib-pg18")
    public static let uuidOssp = OliphauntExtension(sqlName: "uuid-ossp", product: "oliphaunt-extension-contrib-pg18")
}

let oliphauntExtensionRuntimeContracts: [String: (dependencies: [String], sharedPreloads: [String], module: String?)] = [
    "amcheck": (dependencies: [], sharedPreloads: [], module: "amcheck"),
    "auto_explain": (dependencies: [], sharedPreloads: [], module: "auto_explain"),
    "bloom": (dependencies: [], sharedPreloads: [], module: "bloom"),
    "btree_gin": (dependencies: [], sharedPreloads: [], module: "btree_gin"),
    "btree_gist": (dependencies: [], sharedPreloads: [], module: "btree_gist"),
    "citext": (dependencies: [], sharedPreloads: [], module: "citext"),
    "cube": (dependencies: [], sharedPreloads: [], module: "cube"),
    "dict_int": (dependencies: [], sharedPreloads: [], module: "dict_int"),
    "dict_xsyn": (dependencies: [], sharedPreloads: [], module: "dict_xsyn"),
    "earthdistance": (dependencies: ["cube"], sharedPreloads: [], module: "earthdistance"),
    "file_fdw": (dependencies: [], sharedPreloads: [], module: "file_fdw"),
    "fuzzystrmatch": (dependencies: [], sharedPreloads: [], module: "fuzzystrmatch"),
    "hstore": (dependencies: [], sharedPreloads: [], module: "hstore"),
    "intarray": (dependencies: [], sharedPreloads: [], module: "_int"),
    "isn": (dependencies: [], sharedPreloads: [], module: "isn"),
    "lo": (dependencies: [], sharedPreloads: [], module: "lo"),
    "ltree": (dependencies: [], sharedPreloads: [], module: "ltree"),
    "pageinspect": (dependencies: [], sharedPreloads: [], module: "pageinspect"),
    "pg_buffercache": (dependencies: [], sharedPreloads: [], module: "pg_buffercache"),
    "pg_freespacemap": (dependencies: [], sharedPreloads: [], module: "pg_freespacemap"),
    "pg_hashids": (dependencies: [], sharedPreloads: [], module: "pg_hashids"),
    "pg_ivm": (dependencies: [], sharedPreloads: [], module: "pg_ivm"),
    "pg_surgery": (dependencies: [], sharedPreloads: [], module: "pg_surgery"),
    "pg_textsearch": (dependencies: [], sharedPreloads: ["pg_textsearch"], module: "pg_textsearch"),
    "pg_trgm": (dependencies: [], sharedPreloads: [], module: "pg_trgm"),
    "pg_uuidv7": (dependencies: [], sharedPreloads: [], module: "pg_uuidv7"),
    "pg_visibility": (dependencies: [], sharedPreloads: [], module: "pg_visibility"),
    "pg_walinspect": (dependencies: [], sharedPreloads: [], module: "pg_walinspect"),
    "pgcrypto": (dependencies: [], sharedPreloads: [], module: "pgcrypto"),
    "pgtap": (dependencies: [], sharedPreloads: [], module: nil),
    "postgis": (dependencies: [], sharedPreloads: [], module: "postgis-3"),
    "seg": (dependencies: [], sharedPreloads: [], module: "seg"),
    "tablefunc": (dependencies: [], sharedPreloads: [], module: "tablefunc"),
    "tcn": (dependencies: [], sharedPreloads: [], module: "tcn"),
    "tsm_system_rows": (dependencies: [], sharedPreloads: [], module: "tsm_system_rows"),
    "tsm_system_time": (dependencies: [], sharedPreloads: [], module: "tsm_system_time"),
    "unaccent": (dependencies: [], sharedPreloads: [], module: "unaccent"),
    "uuid-ossp": (dependencies: [], sharedPreloads: [], module: "uuid-ossp"),
    "vector": (dependencies: [], sharedPreloads: [], module: "vector"),
]
