// This file is generated by src/extensions/tools/check-extension-model.sh.
// Do not edit by hand.

import Foundation

/// An explicitly selected extension. Selection does not run CREATE EXTENSION.
public struct OliphauntExtension: Sendable, Equatable {
    public let sqlName: String
    private let product: String?
    private let version: String?
    private let registration: @Sendable () throws -> Void

    /// Select an extension whose native resources are already linked by the application.
    public init(sqlName: String) throws {
        _ = try OliphauntRuntimeResources.validateExtensionIds([sqlName])
        self.sqlName = sqlName
        self.product = nil
        self.version = nil
        self.registration = {}
    }

    /// Used by generated SwiftPM resource products to register their own verified payload.
    public init(sqlName: String, product: String? = nil, version: String? = nil, registration: @escaping @Sendable () throws -> Void) {
        self.sqlName = sqlName
        self.product = product
        self.version = version
        self.registration = registration
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.sqlName == rhs.sqlName && lhs.product == rhs.product && lhs.version == rhs.version
    }

    func prepare() throws { try registration() }

    public static let amcheck = OliphauntExtension(sqlName: "amcheck", registration: {})
    public static let autoExplain = OliphauntExtension(sqlName: "auto_explain", registration: {})
    public static let bloom = OliphauntExtension(sqlName: "bloom", registration: {})
    public static let btreeGin = OliphauntExtension(sqlName: "btree_gin", registration: {})
    public static let btreeGist = OliphauntExtension(sqlName: "btree_gist", registration: {})
    public static let citext = OliphauntExtension(sqlName: "citext", registration: {})
    public static let cube = OliphauntExtension(sqlName: "cube", registration: {})
    public static let dictInt = OliphauntExtension(sqlName: "dict_int", registration: {})
    public static let dictXsyn = OliphauntExtension(sqlName: "dict_xsyn", registration: {})
    public static let earthdistance = OliphauntExtension(sqlName: "earthdistance", registration: {})
    public static let fileFdw = OliphauntExtension(sqlName: "file_fdw", registration: {})
    public static let fuzzystrmatch = OliphauntExtension(sqlName: "fuzzystrmatch", registration: {})
    public static let hstore = OliphauntExtension(sqlName: "hstore", registration: {})
    public static let intarray = OliphauntExtension(sqlName: "intarray", registration: {})
    public static let isn = OliphauntExtension(sqlName: "isn", registration: {})
    public static let lo = OliphauntExtension(sqlName: "lo", registration: {})
    public static let ltree = OliphauntExtension(sqlName: "ltree", registration: {})
    public static let pageinspect = OliphauntExtension(sqlName: "pageinspect", registration: {})
    public static let pgBuffercache = OliphauntExtension(sqlName: "pg_buffercache", registration: {})
    public static let pgFreespacemap = OliphauntExtension(sqlName: "pg_freespacemap", registration: {})
    public static let pgHashids = OliphauntExtension(sqlName: "pg_hashids", registration: {})
    public static let pgIvm = OliphauntExtension(sqlName: "pg_ivm", registration: {})
    public static let pgSurgery = OliphauntExtension(sqlName: "pg_surgery", registration: {})
    public static let pgTextsearch = OliphauntExtension(sqlName: "pg_textsearch", registration: {})
    public static let pgTrgm = OliphauntExtension(sqlName: "pg_trgm", registration: {})
    public static let pgUuidv7 = OliphauntExtension(sqlName: "pg_uuidv7", registration: {})
    public static let pgVisibility = OliphauntExtension(sqlName: "pg_visibility", registration: {})
    public static let pgWalinspect = OliphauntExtension(sqlName: "pg_walinspect", registration: {})
    public static let pgcrypto = OliphauntExtension(sqlName: "pgcrypto", registration: {})
    public static let pgtap = OliphauntExtension(sqlName: "pgtap", registration: {})
    public static let postgis = OliphauntExtension(sqlName: "postgis", registration: {})
    public static let seg = OliphauntExtension(sqlName: "seg", registration: {})
    public static let tablefunc = OliphauntExtension(sqlName: "tablefunc", registration: {})
    public static let tcn = OliphauntExtension(sqlName: "tcn", registration: {})
    public static let tsmSystemRows = OliphauntExtension(sqlName: "tsm_system_rows", registration: {})
    public static let tsmSystemTime = OliphauntExtension(sqlName: "tsm_system_time", registration: {})
    public static let unaccent = OliphauntExtension(sqlName: "unaccent", registration: {})
    public static let uuidOssp = OliphauntExtension(sqlName: "uuid-ossp", registration: {})
    public static let vector = OliphauntExtension(sqlName: "vector", registration: {})
}
