[package]
name = "oliphaunt-mobile-bindings"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
bindgen = ["uniffi/cli"]

[dependencies]
oliphaunt = { path = "../sdk", default-features = false, features = ["mobile-bindings"] }
liboliphaunt-native-bindings = { path = "../liboliphaunt-native" }
uniffi = { version = "=0.32.1", default-features = false }
thiserror = "2"

[[bin]]
name = "oliphaunt-mobile-bindgen"
path = "src/bin/bindgen.rs"
required-features = ["bindgen"]
