// @generated by `cargo run -p xtask -- extensions generate`

/// Select `amcheck`.
pub const AMCHECK: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "amcheck",
    package: None,
};
/// Select `auto_explain`.
pub const AUTO_EXPLAIN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "auto_explain",
    package: None,
};
/// Select `bloom`.
pub const BLOOM: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "bloom",
    package: None,
};
/// Select `btree_gin`.
pub const BTREE_GIN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "btree_gin",
    package: None,
};
/// Select `btree_gist`.
pub const BTREE_GIST: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "btree_gist",
    package: None,
};
/// Select `citext`.
pub const CITEXT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "citext",
    package: None,
};
/// Select `cube`.
pub const CUBE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "cube",
    package: None,
};
/// Select `dict_int`.
pub const DICT_INT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "dict_int",
    package: None,
};
/// Select `dict_xsyn`.
pub const DICT_XSYN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "dict_xsyn",
    package: None,
};
/// Select `earthdistance`.
pub const EARTHDISTANCE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "earthdistance",
    package: None,
};
/// Select `file_fdw`.
pub const FILE_FDW: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "file_fdw",
    package: None,
};
/// Select `fuzzystrmatch`.
pub const FUZZYSTRMATCH: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "fuzzystrmatch",
    package: None,
};
/// Select `hstore`.
pub const HSTORE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "hstore",
    package: None,
};
/// Select `intarray`.
pub const INTARRAY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "intarray",
    package: None,
};
/// Select `isn`.
pub const ISN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "isn",
    package: None,
};
/// Select `lo`.
pub const LO: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "lo",
    package: None,
};
/// Select `ltree`.
pub const LTREE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "ltree",
    package: None,
};
/// Select `pageinspect`.
pub const PAGEINSPECT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pageinspect",
    package: None,
};
/// Select `pg_buffercache`.
pub const PG_BUFFERCACHE: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_buffercache",
    package: None,
};
/// Select `pg_freespacemap`.
pub const PG_FREESPACEMAP: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_freespacemap",
    package: None,
};
/// Select `pg_surgery`.
pub const PG_SURGERY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_surgery",
    package: None,
};
/// Select `pg_trgm`.
pub const PG_TRGM: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_trgm",
    package: None,
};
/// Select `pg_visibility`.
pub const PG_VISIBILITY: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_visibility",
    package: None,
};
/// Select `pg_walinspect`.
pub const PG_WALINSPECT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pg_walinspect",
    package: None,
};
/// Select `pgcrypto`.
pub const PGCRYPTO: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "pgcrypto",
    package: None,
};
/// Select `seg`.
pub const SEG: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "seg",
    package: None,
};
/// Select `tablefunc`.
pub const TABLEFUNC: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tablefunc",
    package: None,
};
/// Select `tcn`.
pub const TCN: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tcn",
    package: None,
};
/// Select `tsm_system_rows`.
pub const TSM_SYSTEM_ROWS: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tsm_system_rows",
    package: None,
};
/// Select `tsm_system_time`.
pub const TSM_SYSTEM_TIME: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "tsm_system_time",
    package: None,
};
/// Select `unaccent`.
pub const UNACCENT: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "unaccent",
    package: None,
};
/// Select `uuid-ossp`.
pub const UUID_OSSP: crate::ExtensionDescriptor = crate::ExtensionDescriptor {
    sql_name: "uuid-ossp",
    package: None,
};
