// @generated by `cargo run -p xtask -- extensions generate`

use super::{Extension, ExtensionNativeModule, ExtensionSetup};

const EMPTY_SQL_NAMES: &[&str] = &[];
const EMPTY_SQL: &[&str] = &[];
const EMPTY_NATIVE_MODULES: &[ExtensionNativeModule] = &[];

const CANDIDATE_AMCHECK_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_AMCHECK_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_AMCHECK_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_AMCHECK_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_AMCHECK: Extension = Extension::new(
    "amcheck",
    "amcheck",
    "extensions/amcheck.tar.zst",
    CANDIDATE_AMCHECK_NATIVE_SUPPORT_MODULES,
    Some("amcheck.so"),
    Some("extension:amcheck"),
    CANDIDATE_AMCHECK_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_AMCHECK_LOAD_SQL,
        CANDIDATE_AMCHECK_POST_CREATE_SQL,
    ),
);

const CANDIDATE_AUTO_EXPLAIN_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_AUTO_EXPLAIN_LOAD_SQL: &[&str] = &[
    "LOAD 'auto_explain';",
    "SET auto_explain.log_min_duration = '0';",
    "SET auto_explain.log_analyze = 'true';",
    "SET auto_explain.log_level = 'NOTICE';",
];
const CANDIDATE_AUTO_EXPLAIN_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_AUTO_EXPLAIN_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_AUTO_EXPLAIN: Extension = Extension::new(
    "auto_explain",
    "auto_explain",
    "extensions/auto_explain.tar.zst",
    CANDIDATE_AUTO_EXPLAIN_NATIVE_SUPPORT_MODULES,
    Some("auto_explain.so"),
    Some("extension:auto_explain"),
    CANDIDATE_AUTO_EXPLAIN_DEPENDENCIES,
    ExtensionSetup::new(
        false,
        None,
        CANDIDATE_AUTO_EXPLAIN_LOAD_SQL,
        CANDIDATE_AUTO_EXPLAIN_POST_CREATE_SQL,
    ),
);

const CANDIDATE_BLOOM_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_BLOOM_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BLOOM_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BLOOM_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_BLOOM: Extension = Extension::new(
    "bloom",
    "bloom",
    "extensions/bloom.tar.zst",
    CANDIDATE_BLOOM_NATIVE_SUPPORT_MODULES,
    Some("bloom.so"),
    Some("extension:bloom"),
    CANDIDATE_BLOOM_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_BLOOM_LOAD_SQL,
        CANDIDATE_BLOOM_POST_CREATE_SQL,
    ),
);

const CANDIDATE_BTREE_GIN_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_BTREE_GIN_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BTREE_GIN_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BTREE_GIN_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_BTREE_GIN: Extension = Extension::new(
    "btree_gin",
    "btree_gin",
    "extensions/btree_gin.tar.zst",
    CANDIDATE_BTREE_GIN_NATIVE_SUPPORT_MODULES,
    Some("btree_gin.so"),
    Some("extension:btree_gin"),
    CANDIDATE_BTREE_GIN_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_BTREE_GIN_LOAD_SQL,
        CANDIDATE_BTREE_GIN_POST_CREATE_SQL,
    ),
);

const CANDIDATE_BTREE_GIST_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_BTREE_GIST_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BTREE_GIST_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_BTREE_GIST_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_BTREE_GIST: Extension = Extension::new(
    "btree_gist",
    "btree_gist",
    "extensions/btree_gist.tar.zst",
    CANDIDATE_BTREE_GIST_NATIVE_SUPPORT_MODULES,
    Some("btree_gist.so"),
    Some("extension:btree_gist"),
    CANDIDATE_BTREE_GIST_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_BTREE_GIST_LOAD_SQL,
        CANDIDATE_BTREE_GIST_POST_CREATE_SQL,
    ),
);

const CANDIDATE_CITEXT_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_CITEXT_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_CITEXT_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_CITEXT_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_CITEXT: Extension = Extension::new(
    "citext",
    "citext",
    "extensions/citext.tar.zst",
    CANDIDATE_CITEXT_NATIVE_SUPPORT_MODULES,
    Some("citext.so"),
    Some("extension:citext"),
    CANDIDATE_CITEXT_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_CITEXT_LOAD_SQL,
        CANDIDATE_CITEXT_POST_CREATE_SQL,
    ),
);

const CANDIDATE_CUBE_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_CUBE_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_CUBE_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_CUBE_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_CUBE: Extension = Extension::new(
    "cube",
    "cube",
    "extensions/cube.tar.zst",
    CANDIDATE_CUBE_NATIVE_SUPPORT_MODULES,
    Some("cube.so"),
    Some("extension:cube"),
    CANDIDATE_CUBE_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_CUBE_LOAD_SQL,
        CANDIDATE_CUBE_POST_CREATE_SQL,
    ),
);

const CANDIDATE_DICT_INT_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_DICT_INT_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_DICT_INT_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_DICT_INT_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_DICT_INT: Extension = Extension::new(
    "dict_int",
    "dict_int",
    "extensions/dict_int.tar.zst",
    CANDIDATE_DICT_INT_NATIVE_SUPPORT_MODULES,
    Some("dict_int.so"),
    Some("extension:dict_int"),
    CANDIDATE_DICT_INT_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_DICT_INT_LOAD_SQL,
        CANDIDATE_DICT_INT_POST_CREATE_SQL,
    ),
);

const CANDIDATE_DICT_XSYN_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_DICT_XSYN_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_DICT_XSYN_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_DICT_XSYN_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_DICT_XSYN: Extension = Extension::new(
    "dict_xsyn",
    "dict_xsyn",
    "extensions/dict_xsyn.tar.zst",
    CANDIDATE_DICT_XSYN_NATIVE_SUPPORT_MODULES,
    Some("dict_xsyn.so"),
    Some("extension:dict_xsyn"),
    CANDIDATE_DICT_XSYN_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_DICT_XSYN_LOAD_SQL,
        CANDIDATE_DICT_XSYN_POST_CREATE_SQL,
    ),
);

const CANDIDATE_EARTHDISTANCE_DEPENDENCIES: &[&str] = &["cube"];
const CANDIDATE_EARTHDISTANCE_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_EARTHDISTANCE_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_EARTHDISTANCE_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_EARTHDISTANCE: Extension = Extension::new(
    "earthdistance",
    "earthdistance",
    "extensions/earthdistance.tar.zst",
    CANDIDATE_EARTHDISTANCE_NATIVE_SUPPORT_MODULES,
    Some("earthdistance.so"),
    Some("extension:earthdistance"),
    CANDIDATE_EARTHDISTANCE_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_EARTHDISTANCE_LOAD_SQL,
        CANDIDATE_EARTHDISTANCE_POST_CREATE_SQL,
    ),
);

const CANDIDATE_FILE_FDW_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_FILE_FDW_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_FILE_FDW_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_FILE_FDW_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_FILE_FDW: Extension = Extension::new(
    "file_fdw",
    "file_fdw",
    "extensions/file_fdw.tar.zst",
    CANDIDATE_FILE_FDW_NATIVE_SUPPORT_MODULES,
    Some("file_fdw.so"),
    Some("extension:file_fdw"),
    CANDIDATE_FILE_FDW_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_FILE_FDW_LOAD_SQL,
        CANDIDATE_FILE_FDW_POST_CREATE_SQL,
    ),
);

const CANDIDATE_FUZZYSTRMATCH_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_FUZZYSTRMATCH_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_FUZZYSTRMATCH_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_FUZZYSTRMATCH_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_FUZZYSTRMATCH: Extension = Extension::new(
    "fuzzystrmatch",
    "fuzzystrmatch",
    "extensions/fuzzystrmatch.tar.zst",
    CANDIDATE_FUZZYSTRMATCH_NATIVE_SUPPORT_MODULES,
    Some("fuzzystrmatch.so"),
    Some("extension:fuzzystrmatch"),
    CANDIDATE_FUZZYSTRMATCH_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_FUZZYSTRMATCH_LOAD_SQL,
        CANDIDATE_FUZZYSTRMATCH_POST_CREATE_SQL,
    ),
);

const CANDIDATE_HSTORE_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_HSTORE_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_HSTORE_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_HSTORE_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_HSTORE: Extension = Extension::new(
    "hstore",
    "hstore",
    "extensions/hstore.tar.zst",
    CANDIDATE_HSTORE_NATIVE_SUPPORT_MODULES,
    Some("hstore.so"),
    Some("extension:hstore"),
    CANDIDATE_HSTORE_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_HSTORE_LOAD_SQL,
        CANDIDATE_HSTORE_POST_CREATE_SQL,
    ),
);

const CANDIDATE_INTARRAY_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_INTARRAY_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_INTARRAY_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_INTARRAY_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_INTARRAY: Extension = Extension::new(
    "intarray",
    "intarray",
    "extensions/intarray.tar.zst",
    CANDIDATE_INTARRAY_NATIVE_SUPPORT_MODULES,
    Some("_int.so"),
    Some("extension:intarray"),
    CANDIDATE_INTARRAY_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_INTARRAY_LOAD_SQL,
        CANDIDATE_INTARRAY_POST_CREATE_SQL,
    ),
);

const CANDIDATE_ISN_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_ISN_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_ISN_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_ISN_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_ISN: Extension = Extension::new(
    "isn",
    "isn",
    "extensions/isn.tar.zst",
    CANDIDATE_ISN_NATIVE_SUPPORT_MODULES,
    Some("isn.so"),
    Some("extension:isn"),
    CANDIDATE_ISN_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_ISN_LOAD_SQL,
        CANDIDATE_ISN_POST_CREATE_SQL,
    ),
);

const CANDIDATE_LO_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_LO_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_LO_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_LO_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_LO: Extension = Extension::new(
    "lo",
    "lo",
    "extensions/lo.tar.zst",
    CANDIDATE_LO_NATIVE_SUPPORT_MODULES,
    Some("lo.so"),
    Some("extension:lo"),
    CANDIDATE_LO_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_LO_LOAD_SQL,
        CANDIDATE_LO_POST_CREATE_SQL,
    ),
);

const CANDIDATE_LTREE_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_LTREE_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_LTREE_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_LTREE_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_LTREE: Extension = Extension::new(
    "ltree",
    "ltree",
    "extensions/ltree.tar.zst",
    CANDIDATE_LTREE_NATIVE_SUPPORT_MODULES,
    Some("ltree.so"),
    Some("extension:ltree"),
    CANDIDATE_LTREE_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_LTREE_LOAD_SQL,
        CANDIDATE_LTREE_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PAGEINSPECT_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PAGEINSPECT_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PAGEINSPECT_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PAGEINSPECT_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PAGEINSPECT: Extension = Extension::new(
    "pageinspect",
    "pageinspect",
    "extensions/pageinspect.tar.zst",
    CANDIDATE_PAGEINSPECT_NATIVE_SUPPORT_MODULES,
    Some("pageinspect.so"),
    Some("extension:pageinspect"),
    CANDIDATE_PAGEINSPECT_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PAGEINSPECT_LOAD_SQL,
        CANDIDATE_PAGEINSPECT_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_BUFFERCACHE_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_BUFFERCACHE_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_BUFFERCACHE_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_BUFFERCACHE_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_BUFFERCACHE: Extension = Extension::new(
    "pg_buffercache",
    "pg_buffercache",
    "extensions/pg_buffercache.tar.zst",
    CANDIDATE_PG_BUFFERCACHE_NATIVE_SUPPORT_MODULES,
    Some("pg_buffercache.so"),
    Some("extension:pg_buffercache"),
    CANDIDATE_PG_BUFFERCACHE_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_BUFFERCACHE_LOAD_SQL,
        CANDIDATE_PG_BUFFERCACHE_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_FREESPACEMAP_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_FREESPACEMAP_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_FREESPACEMAP_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_FREESPACEMAP_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_FREESPACEMAP: Extension = Extension::new(
    "pg_freespacemap",
    "pg_freespacemap",
    "extensions/pg_freespacemap.tar.zst",
    CANDIDATE_PG_FREESPACEMAP_NATIVE_SUPPORT_MODULES,
    Some("pg_freespacemap.so"),
    Some("extension:pg_freespacemap"),
    CANDIDATE_PG_FREESPACEMAP_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_FREESPACEMAP_LOAD_SQL,
        CANDIDATE_PG_FREESPACEMAP_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_HASHIDS_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_HASHIDS_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_HASHIDS_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_HASHIDS_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_HASHIDS: Extension = Extension::new(
    "pg_hashids",
    "pg_hashids",
    "extensions/pg_hashids.tar.zst",
    CANDIDATE_PG_HASHIDS_NATIVE_SUPPORT_MODULES,
    Some("pg_hashids.so"),
    Some("extension:pg_hashids"),
    CANDIDATE_PG_HASHIDS_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_HASHIDS_LOAD_SQL,
        CANDIDATE_PG_HASHIDS_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_IVM_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_IVM_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_IVM_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_IVM_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_IVM: Extension = Extension::new(
    "pg_ivm",
    "pg_ivm",
    "extensions/pg_ivm.tar.zst",
    CANDIDATE_PG_IVM_NATIVE_SUPPORT_MODULES,
    Some("pg_ivm.so"),
    Some("extension:pg_ivm"),
    CANDIDATE_PG_IVM_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_IVM_LOAD_SQL,
        CANDIDATE_PG_IVM_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_SURGERY_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_SURGERY_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_SURGERY_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_SURGERY_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_SURGERY: Extension = Extension::new(
    "pg_surgery",
    "pg_surgery",
    "extensions/pg_surgery.tar.zst",
    CANDIDATE_PG_SURGERY_NATIVE_SUPPORT_MODULES,
    Some("pg_surgery.so"),
    Some("extension:pg_surgery"),
    CANDIDATE_PG_SURGERY_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_SURGERY_LOAD_SQL,
        CANDIDATE_PG_SURGERY_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_TEXTSEARCH_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_TEXTSEARCH_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_TEXTSEARCH_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_TEXTSEARCH_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_TEXTSEARCH: Extension = Extension::new(
    "pg_textsearch",
    "pg_textsearch",
    "extensions/pg_textsearch.tar.zst",
    CANDIDATE_PG_TEXTSEARCH_NATIVE_SUPPORT_MODULES,
    Some("pg_textsearch.so"),
    Some("extension:pg_textsearch"),
    CANDIDATE_PG_TEXTSEARCH_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_TEXTSEARCH_LOAD_SQL,
        CANDIDATE_PG_TEXTSEARCH_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_TRGM_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_TRGM_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_TRGM_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_TRGM_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_TRGM: Extension = Extension::new(
    "pg_trgm",
    "pg_trgm",
    "extensions/pg_trgm.tar.zst",
    CANDIDATE_PG_TRGM_NATIVE_SUPPORT_MODULES,
    Some("pg_trgm.so"),
    Some("extension:pg_trgm"),
    CANDIDATE_PG_TRGM_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_TRGM_LOAD_SQL,
        CANDIDATE_PG_TRGM_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_UUIDV7_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_UUIDV7_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_UUIDV7_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_UUIDV7_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_UUIDV7: Extension = Extension::new(
    "pg_uuidv7",
    "pg_uuidv7",
    "extensions/pg_uuidv7.tar.zst",
    CANDIDATE_PG_UUIDV7_NATIVE_SUPPORT_MODULES,
    Some("pg_uuidv7.so"),
    Some("extension:pg_uuidv7"),
    CANDIDATE_PG_UUIDV7_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_UUIDV7_LOAD_SQL,
        CANDIDATE_PG_UUIDV7_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_VISIBILITY_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_VISIBILITY_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_VISIBILITY_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_VISIBILITY_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_VISIBILITY: Extension = Extension::new(
    "pg_visibility",
    "pg_visibility",
    "extensions/pg_visibility.tar.zst",
    CANDIDATE_PG_VISIBILITY_NATIVE_SUPPORT_MODULES,
    Some("pg_visibility.so"),
    Some("extension:pg_visibility"),
    CANDIDATE_PG_VISIBILITY_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_VISIBILITY_LOAD_SQL,
        CANDIDATE_PG_VISIBILITY_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PG_WALINSPECT_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PG_WALINSPECT_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_WALINSPECT_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PG_WALINSPECT_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PG_WALINSPECT: Extension = Extension::new(
    "pg_walinspect",
    "pg_walinspect",
    "extensions/pg_walinspect.tar.zst",
    CANDIDATE_PG_WALINSPECT_NATIVE_SUPPORT_MODULES,
    Some("pg_walinspect.so"),
    Some("extension:pg_walinspect"),
    CANDIDATE_PG_WALINSPECT_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PG_WALINSPECT_LOAD_SQL,
        CANDIDATE_PG_WALINSPECT_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PGCRYPTO_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PGCRYPTO_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PGCRYPTO_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PGCRYPTO_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PGCRYPTO: Extension = Extension::new(
    "pgcrypto",
    "pgcrypto",
    "extensions/pgcrypto.tar.zst",
    CANDIDATE_PGCRYPTO_NATIVE_SUPPORT_MODULES,
    Some("pgcrypto.so"),
    Some("extension:pgcrypto"),
    CANDIDATE_PGCRYPTO_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        None,
        CANDIDATE_PGCRYPTO_LOAD_SQL,
        CANDIDATE_PGCRYPTO_POST_CREATE_SQL,
    ),
);

const CANDIDATE_PGTAP_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_PGTAP_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PGTAP_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_PGTAP_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_PGTAP: Extension = Extension::new(
    "pgtap",
    "pgtap",
    "extensions/pgtap.tar.zst",
    CANDIDATE_PGTAP_NATIVE_SUPPORT_MODULES,
    None,
    None,
    CANDIDATE_PGTAP_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_PGTAP_LOAD_SQL,
        CANDIDATE_PGTAP_POST_CREATE_SQL,
    ),
);

const CANDIDATE_POSTGIS_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_POSTGIS_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_POSTGIS_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_POSTGIS_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    &[ExtensionNativeModule::new(
        "lib/postgresql/liboliphaunt_postgis_deps.so",
        Some("extension:postgis:postgis_deps"),
    )];

pub(crate) const CANDIDATE_POSTGIS: Extension = Extension::new(
    "PostGIS",
    "postgis",
    "extensions/postgis.tar.zst",
    CANDIDATE_POSTGIS_NATIVE_SUPPORT_MODULES,
    Some("postgis-3.so"),
    Some("extension:postgis"),
    CANDIDATE_POSTGIS_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        None,
        CANDIDATE_POSTGIS_LOAD_SQL,
        CANDIDATE_POSTGIS_POST_CREATE_SQL,
    ),
);

const CANDIDATE_SEG_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_SEG_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_SEG_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_SEG_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_SEG: Extension = Extension::new(
    "seg",
    "seg",
    "extensions/seg.tar.zst",
    CANDIDATE_SEG_NATIVE_SUPPORT_MODULES,
    Some("seg.so"),
    Some("extension:seg"),
    CANDIDATE_SEG_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_SEG_LOAD_SQL,
        CANDIDATE_SEG_POST_CREATE_SQL,
    ),
);

const CANDIDATE_TABLEFUNC_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_TABLEFUNC_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TABLEFUNC_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TABLEFUNC_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_TABLEFUNC: Extension = Extension::new(
    "tablefunc",
    "tablefunc",
    "extensions/tablefunc.tar.zst",
    CANDIDATE_TABLEFUNC_NATIVE_SUPPORT_MODULES,
    Some("tablefunc.so"),
    Some("extension:tablefunc"),
    CANDIDATE_TABLEFUNC_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_TABLEFUNC_LOAD_SQL,
        CANDIDATE_TABLEFUNC_POST_CREATE_SQL,
    ),
);

const CANDIDATE_TCN_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_TCN_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TCN_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TCN_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_TCN: Extension = Extension::new(
    "tcn",
    "tcn",
    "extensions/tcn.tar.zst",
    CANDIDATE_TCN_NATIVE_SUPPORT_MODULES,
    Some("tcn.so"),
    Some("extension:tcn"),
    CANDIDATE_TCN_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_TCN_LOAD_SQL,
        CANDIDATE_TCN_POST_CREATE_SQL,
    ),
);

const CANDIDATE_TSM_SYSTEM_ROWS_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_TSM_SYSTEM_ROWS_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TSM_SYSTEM_ROWS_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TSM_SYSTEM_ROWS_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_TSM_SYSTEM_ROWS: Extension = Extension::new(
    "tsm_system_rows",
    "tsm_system_rows",
    "extensions/tsm_system_rows.tar.zst",
    CANDIDATE_TSM_SYSTEM_ROWS_NATIVE_SUPPORT_MODULES,
    Some("tsm_system_rows.so"),
    Some("extension:tsm_system_rows"),
    CANDIDATE_TSM_SYSTEM_ROWS_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_TSM_SYSTEM_ROWS_LOAD_SQL,
        CANDIDATE_TSM_SYSTEM_ROWS_POST_CREATE_SQL,
    ),
);

const CANDIDATE_TSM_SYSTEM_TIME_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_TSM_SYSTEM_TIME_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TSM_SYSTEM_TIME_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_TSM_SYSTEM_TIME_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] =
    EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_TSM_SYSTEM_TIME: Extension = Extension::new(
    "tsm_system_time",
    "tsm_system_time",
    "extensions/tsm_system_time.tar.zst",
    CANDIDATE_TSM_SYSTEM_TIME_NATIVE_SUPPORT_MODULES,
    Some("tsm_system_time.so"),
    Some("extension:tsm_system_time"),
    CANDIDATE_TSM_SYSTEM_TIME_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_TSM_SYSTEM_TIME_LOAD_SQL,
        CANDIDATE_TSM_SYSTEM_TIME_POST_CREATE_SQL,
    ),
);

const CANDIDATE_UNACCENT_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_UNACCENT_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_UNACCENT_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_UNACCENT_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_UNACCENT: Extension = Extension::new(
    "unaccent",
    "unaccent",
    "extensions/unaccent.tar.zst",
    CANDIDATE_UNACCENT_NATIVE_SUPPORT_MODULES,
    Some("unaccent.so"),
    Some("extension:unaccent"),
    CANDIDATE_UNACCENT_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_UNACCENT_LOAD_SQL,
        CANDIDATE_UNACCENT_POST_CREATE_SQL,
    ),
);

const CANDIDATE_UUID_OSSP_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_UUID_OSSP_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_UUID_OSSP_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_UUID_OSSP_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_UUID_OSSP: Extension = Extension::new(
    "uuid-ossp",
    "uuid-ossp",
    "extensions/uuid-ossp.tar.zst",
    CANDIDATE_UUID_OSSP_NATIVE_SUPPORT_MODULES,
    Some("uuid-ossp.so"),
    Some("extension:uuid-ossp"),
    CANDIDATE_UUID_OSSP_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_UUID_OSSP_LOAD_SQL,
        CANDIDATE_UUID_OSSP_POST_CREATE_SQL,
    ),
);

const CANDIDATE_VECTOR_DEPENDENCIES: &[&str] = EMPTY_SQL_NAMES;
const CANDIDATE_VECTOR_LOAD_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_VECTOR_POST_CREATE_SQL: &[&str] = EMPTY_SQL;
const CANDIDATE_VECTOR_NATIVE_SUPPORT_MODULES: &[ExtensionNativeModule] = EMPTY_NATIVE_MODULES;

pub(crate) const CANDIDATE_VECTOR: Extension = Extension::new(
    "pgvector",
    "vector",
    "extensions/vector.tar.zst",
    CANDIDATE_VECTOR_NATIVE_SUPPORT_MODULES,
    Some("vector.so"),
    Some("extension:vector"),
    CANDIDATE_VECTOR_DEPENDENCIES,
    ExtensionSetup::new(
        true,
        Some("pg_catalog"),
        CANDIDATE_VECTOR_LOAD_SQL,
        CANDIDATE_VECTOR_POST_CREATE_SQL,
    ),
);

pub const AMCHECK: Extension = CANDIDATE_AMCHECK;
pub const AUTO_EXPLAIN: Extension = CANDIDATE_AUTO_EXPLAIN;
pub const BLOOM: Extension = CANDIDATE_BLOOM;
pub const BTREE_GIN: Extension = CANDIDATE_BTREE_GIN;
pub const BTREE_GIST: Extension = CANDIDATE_BTREE_GIST;
pub const CITEXT: Extension = CANDIDATE_CITEXT;
pub const CUBE: Extension = CANDIDATE_CUBE;
pub const DICT_INT: Extension = CANDIDATE_DICT_INT;
pub const DICT_XSYN: Extension = CANDIDATE_DICT_XSYN;
pub const EARTHDISTANCE: Extension = CANDIDATE_EARTHDISTANCE;
pub const FILE_FDW: Extension = CANDIDATE_FILE_FDW;
pub const FUZZYSTRMATCH: Extension = CANDIDATE_FUZZYSTRMATCH;
pub const HSTORE: Extension = CANDIDATE_HSTORE;
pub const INTARRAY: Extension = CANDIDATE_INTARRAY;
pub const ISN: Extension = CANDIDATE_ISN;
pub const LO: Extension = CANDIDATE_LO;
pub const LTREE: Extension = CANDIDATE_LTREE;
pub const PAGEINSPECT: Extension = CANDIDATE_PAGEINSPECT;
pub const PG_BUFFERCACHE: Extension = CANDIDATE_PG_BUFFERCACHE;
pub const PG_FREESPACEMAP: Extension = CANDIDATE_PG_FREESPACEMAP;
pub const PG_HASHIDS: Extension = CANDIDATE_PG_HASHIDS;
pub const PG_IVM: Extension = CANDIDATE_PG_IVM;
pub const PG_SURGERY: Extension = CANDIDATE_PG_SURGERY;
pub const PG_TEXTSEARCH: Extension = CANDIDATE_PG_TEXTSEARCH;
pub const PG_TRGM: Extension = CANDIDATE_PG_TRGM;
pub const PG_UUIDV7: Extension = CANDIDATE_PG_UUIDV7;
pub const PG_VISIBILITY: Extension = CANDIDATE_PG_VISIBILITY;
pub const PG_WALINSPECT: Extension = CANDIDATE_PG_WALINSPECT;
pub const PGCRYPTO: Extension = CANDIDATE_PGCRYPTO;
pub const PGTAP: Extension = CANDIDATE_PGTAP;
pub const POSTGIS: Extension = CANDIDATE_POSTGIS;
pub const SEG: Extension = CANDIDATE_SEG;
pub const TABLEFUNC: Extension = CANDIDATE_TABLEFUNC;
pub const TCN: Extension = CANDIDATE_TCN;
pub const TSM_SYSTEM_ROWS: Extension = CANDIDATE_TSM_SYSTEM_ROWS;
pub const TSM_SYSTEM_TIME: Extension = CANDIDATE_TSM_SYSTEM_TIME;
pub const UNACCENT: Extension = CANDIDATE_UNACCENT;
pub const UUID_OSSP: Extension = CANDIDATE_UUID_OSSP;
pub const VECTOR: Extension = CANDIDATE_VECTOR;

pub const ALL: &[Extension] = &[
    AMCHECK,
    AUTO_EXPLAIN,
    BLOOM,
    BTREE_GIN,
    BTREE_GIST,
    CITEXT,
    CUBE,
    DICT_INT,
    DICT_XSYN,
    EARTHDISTANCE,
    FILE_FDW,
    FUZZYSTRMATCH,
    HSTORE,
    INTARRAY,
    ISN,
    LO,
    LTREE,
    PAGEINSPECT,
    PG_BUFFERCACHE,
    PG_FREESPACEMAP,
    PG_HASHIDS,
    PG_IVM,
    PG_SURGERY,
    PG_TEXTSEARCH,
    PG_TRGM,
    PG_UUIDV7,
    PG_VISIBILITY,
    PG_WALINSPECT,
    PGCRYPTO,
    PGTAP,
    POSTGIS,
    SEG,
    TABLEFUNC,
    TCN,
    TSM_SYSTEM_ROWS,
    TSM_SYSTEM_TIME,
    UNACCENT,
    UUID_OSSP,
    VECTOR,
];
pub(crate) const CANDIDATES: &[Extension] = &[
    CANDIDATE_AMCHECK,
    CANDIDATE_AUTO_EXPLAIN,
    CANDIDATE_BLOOM,
    CANDIDATE_BTREE_GIN,
    CANDIDATE_BTREE_GIST,
    CANDIDATE_CITEXT,
    CANDIDATE_CUBE,
    CANDIDATE_DICT_INT,
    CANDIDATE_DICT_XSYN,
    CANDIDATE_EARTHDISTANCE,
    CANDIDATE_FILE_FDW,
    CANDIDATE_FUZZYSTRMATCH,
    CANDIDATE_HSTORE,
    CANDIDATE_INTARRAY,
    CANDIDATE_ISN,
    CANDIDATE_LO,
    CANDIDATE_LTREE,
    CANDIDATE_PAGEINSPECT,
    CANDIDATE_PG_BUFFERCACHE,
    CANDIDATE_PG_FREESPACEMAP,
    CANDIDATE_PG_HASHIDS,
    CANDIDATE_PG_IVM,
    CANDIDATE_PG_SURGERY,
    CANDIDATE_PG_TEXTSEARCH,
    CANDIDATE_PG_TRGM,
    CANDIDATE_PG_UUIDV7,
    CANDIDATE_PG_VISIBILITY,
    CANDIDATE_PG_WALINSPECT,
    CANDIDATE_PGCRYPTO,
    CANDIDATE_PGTAP,
    CANDIDATE_POSTGIS,
    CANDIDATE_SEG,
    CANDIDATE_TABLEFUNC,
    CANDIDATE_TCN,
    CANDIDATE_TSM_SYSTEM_ROWS,
    CANDIDATE_TSM_SYSTEM_TIME,
    CANDIDATE_UNACCENT,
    CANDIDATE_UUID_OSSP,
    CANDIDATE_VECTOR,
];
