// Generated by postgres-protocol-transport-contract/generate.mjs.
// Edit contract.json, not these ABI limits. See docs/maintainers/runtime-resource-budgets.md.
// Hard buffered-response ceiling, not an eager allocation or streaming limit.
pub(crate) const BUFFERED_PROTOCOL_OUTPUT_LIMIT_BYTES: usize = 67108864;
// Maximum callback slice; independent of socket read and COPY frame sizes.
pub(crate) const PROTOCOL_CALLBACK_CHUNK_BYTES: usize = 65536;
