#!/usr/bin/env node

import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const contractRoot = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(contractRoot, '../../../..');
const contract = JSON.parse(await readFile(resolve(contractRoot, 'contract.json'), 'utf8'));

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const generated = renderGeneratedArtifacts(contract);
  await Promise.all(
    Object.entries(generated).map(async ([path, contents]) => {
      const destination = resolve(repositoryRoot, path);
      if (process.argv.includes('--check')) {
        assert.equal(
          await readFile(destination, 'utf8'),
          contents,
          `${path} is stale; run node src/wasix/runtime/protocol-contract/generate.mjs`,
        );
      } else {
        await writeFile(destination, contents, 'utf8');
      }
    }),
  );
}

export function renderGeneratedArtifacts(value) {
  const modes = Object.fromEntries(value.modes.map(({ name, value: mode }) => [name, mode]));
  const copyStates = Object.fromEntries(
    value.copyStates.map(({ name, value: state }) => [name, state]),
  );
  const rustModes = (names) =>
    names
      .map(
        (name) =>
          `pub(crate) const PROTOCOL_${name.toUpperCase().replaceAll('-', '_')}: i32 = ${modes[name]};\n`,
      )
      .join('');
  const header = `/* Generated by src/wasix/runtime/protocol-contract/generate.mjs. */
#ifndef OLIPHAUNT_WASIX_PROTOCOL_TRANSPORT_CONTRACT_GENERATED_H
#define OLIPHAUNT_WASIX_PROTOCOL_TRANSPORT_CONTRACT_GENERATED_H

#include <stddef.h>

#define OLIPHAUNT_WASIX_BUFFERED_PROTOCOL_OUTPUT_LIMIT ${value.bufferedOutput.limitBytes}U
#define OLIPHAUNT_WASIX_PROTOCOL_CALLBACK_CHUNK_MAX ${value.streamedOutput.callbackChunkMaxBytes}U

#define OLIPHAUNT_WASIX_PROTOCOL_BUFFERED ${modes.buffered}
#define OLIPHAUNT_WASIX_PROTOCOL_STREAM ${modes.stream}
#define OLIPHAUNT_WASIX_PROTOCOL_HYBRID ${modes.hybrid}
#define OLIPHAUNT_WASIX_PROTOCOL_BUFFERED_INPUT_STREAMED_OUTPUT ${modes['buffered-input-streamed-output']}

#define OLIPHAUNT_WASIX_PROTOCOL_COPY_NONE ${copyStates.none}
#define OLIPHAUNT_WASIX_PROTOCOL_COPY_IN ${copyStates.in}
#define OLIPHAUNT_WASIX_PROTOCOL_COPY_OUT ${copyStates.out}
#define OLIPHAUNT_WASIX_PROTOCOL_COPY_BOTH ${copyStates.both}

int oliphaunt_wasix_set_protocol_transport(int mode);
int oliphaunt_wasix_protocol_stream_active(void);
void oliphaunt_wasix_protocol_report_copy_response(int state);
int oliphaunt_wasix_protocol_copy_state(void);
int oliphaunt_wasix_input_reset(void);
void *oliphaunt_wasix_input_reserve(size_t length);
int oliphaunt_wasix_input_commit(size_t length);
size_t oliphaunt_wasix_input_available(void);
int oliphaunt_wasix_output_reset(void);
size_t oliphaunt_wasix_output_len(void);
const void *oliphaunt_wasix_output_data(void);
int oliphaunt_wasix_output_status(void);
int oliphaunt_wasix_pq_flush(void);

#endif
`;
  return {
    'src/wasix/sdks/ts/src/protocol-limits.generated.ts':
      '// Generated by src/wasix/runtime/protocol-contract/generate.mjs.\n' +
      '// Edit contract.json, not this callback limit.\n' +
      `export const PROTOCOL_CALLBACK_CHUNK_BYTES = ${value.streamedOutput.callbackChunkMaxBytes};\n`,
    'src/wasix/sdks/rust/src/oliphaunt/protocol_limits_generated.rs':
      '// Generated by src/wasix/runtime/protocol-contract/generate.mjs.\n' +
      '// Edit contract.json, not these ABI limits. See src/docs/maintainers/runtime-resource-budgets.md.\n' +
      '// Signed i32 bridge length ceiling, not an application quota or eager allocation.\n' +
      `pub(crate) const BUFFERED_PROTOCOL_OUTPUT_LIMIT_BYTES: usize = ${value.bufferedOutput.limitBytes};\n` +
      '// Maximum callback slice; independent of socket read and COPY frame sizes.\n' +
      `pub(crate) const PROTOCOL_CALLBACK_CHUNK_BYTES: usize = ${value.streamedOutput.callbackChunkMaxBytes};\n` +
      rustModes(Object.keys(modes)),
    'src/wasix/browser-host/protocol-contract.generated.rs':
      '// Generated by src/wasix/runtime/protocol-contract/generate.mjs.\n' +
      '// Staged as src/protocol_contract.rs in the patched Wasmer JS host.\n' +
      `pub(crate) const PROTOCOL_CALLBACK_CHUNK_BYTES: usize = ${value.streamedOutput.callbackChunkMaxBytes};\n` +
      rustModes(['buffered', 'hybrid', 'buffered-input-streamed-output']),
    'src/wasix/runtime/assets/build/wasix_shim/oliphaunt_wasix_protocol_contract.generated.h':
      header,
  };
}
