name = "postgis"
url = "https://github.com/postgis/postgis.git"
branch = "3.6.4"
commit = "94d984bd083635c1d253db0f87cf80b32548e406"
source_date_epoch = 1780943336

[extension-control]
sql-name = "postgis"
source-path = "extensions/postgis/postgis.control.in"
source-default-version = "@EXTVERSION@"
default-version = "3.6.4"
