name = "postgis"
url = "https://github.com/postgis/postgis.git"
branch = "3.6.3"
commit = "3d12666588a84b23a3147618eaa9b40b0fe5e796"

[extension-control]
sql-name = "postgis"
source-path = "extensions/postgis/postgis.control.in"
source-default-version = "@EXTVERSION@"
default-version = "3.6.3"
