use std::future::Future;
use std::sync::{Arc, Mutex};
use std::task::{Context, Poll, Wake, Waker};
use std::thread;
use std::time::Duration;

use oliphaunt::{EngineMode, Error, Oliphaunt, ProtocolRequest, QueryParam, Result};

#[test]
fn native_sql_regression_when_env_is_available() {
    if native_runtime_env_is_unavailable() {
        eprintln!("skipping native SQL regression: no native library env var is set");
        return;
    }

    run_mode(EngineMode::NativeDirect, None).unwrap();

    let Some(broker) = option_env!("CARGO_BIN_EXE_oliphaunt-broker") else {
        eprintln!("skipping native broker SQL regression: no broker binary path from Cargo");
        run_mode(EngineMode::NativeServer, None).unwrap();
        return;
    };

    run_mode(EngineMode::NativeBroker, Some(broker)).unwrap();
    run_mode(EngineMode::NativeServer, None).unwrap();
}

fn run_mode(mode: EngineMode, broker: Option<&str>) -> Result<()> {
    eprintln!("native_sql_regression::{mode:?} start");
    let mut builder = Oliphaunt::builder().temporary().engine(mode);
    if let Some(broker) = broker {
        builder = builder.broker_executable(broker);
    }
    let db = block_on(builder.open())?;
    run_schema_types_and_recovery(&db)?;
    block_on(db.close())?;
    eprintln!("native_sql_regression::{mode:?} end");
    Ok(())
}

fn run_schema_types_and_recovery(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE SCHEMA reg;
        CREATE TABLE reg.accounts (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login text NOT NULL UNIQUE,
            balance numeric(12,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
            active boolean NOT NULL DEFAULT true,
            metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
            payload bytea,
            tags text[] NOT NULL DEFAULT ARRAY[]::text[]
        );
        CREATE TABLE reg.account_audit (
            account_id bigint NOT NULL,
            action text NOT NULL
        );
        CREATE FUNCTION reg.audit_account_insert() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            INSERT INTO reg.account_audit(account_id, action)
            VALUES (NEW.id, 'insert');
            RETURN NEW;
        END
        $$;
        CREATE TRIGGER account_insert_audit
        AFTER INSERT ON reg.accounts
        FOR EACH ROW EXECUTE FUNCTION reg.audit_account_insert();
        CREATE VIEW reg.open_accounts AS
        SELECT login, balance FROM reg.accounts WHERE active;
        "#,
    ))?;

    let inserted = block_on(db.query_params(
        r#"
        INSERT INTO reg.accounts(login, balance, active, metadata, payload, tags)
        VALUES ($1, $2::numeric, $3::bool, $4::jsonb, $5::bytea, ARRAY[$6::text, $7::text])
        RETURNING
            id::text,
            login,
            balance::text,
            active::text,
            metadata->>'tier' AS tier,
            encode(payload, 'hex') AS payload_hex,
            array_to_string(tags, ',') AS tags
        "#,
        vec![
            QueryParam::from("alpha@example.com"),
            QueryParam::from("12.50"),
            QueryParam::from(true),
            QueryParam::from(r#"{"tier":"pro"}"#),
            QueryParam::binary([0_u8, 1, 255]),
            QueryParam::from("red"),
            QueryParam::from("blue"),
        ],
    ))?;
    assert_eq!(inserted.row_count(), 1);
    assert_eq!(inserted.get_text(0, "login")?, Some("alpha@example.com"));
    assert_eq!(inserted.get_text(0, "balance")?, Some("12.50"));
    assert_eq!(inserted.get_text(0, "active")?, Some("true"));
    assert_eq!(inserted.get_text(0, "tier")?, Some("pro"));
    assert_eq!(inserted.get_text(0, "payload_hex")?, Some("0001ff"));
    assert_eq!(inserted.get_text(0, "tags")?, Some("red,blue"));
    assert_eq!(inserted.fields()[0].type_oid, 25);

    let audit = block_on(db.query("SELECT count(*)::text AS count FROM reg.account_audit"))?;
    assert_eq!(audit.get_text(0, "count")?, Some("1"));

    let view = block_on(db.query("SELECT login FROM reg.open_accounts"))?;
    assert_eq!(view.get_text(0, "login")?, Some("alpha@example.com"));

    run_curated_postgres_feature_regression(db)?;
    run_icu_collation_regression(db)?;

    let constraint_error = block_on(db.query_params(
        "INSERT INTO reg.accounts(login, balance) VALUES ($1, $2::numeric)",
        [QueryParam::from("bad@example.com"), QueryParam::from("-1")],
    ))
    .unwrap_err();
    assert_postgres_error(
        &constraint_error,
        "23514",
        "accounts_balance_check",
        "constraint error",
    );

    let recovered = block_on(db.query("SELECT count(*)::text AS count FROM reg.accounts"))?;
    assert_eq!(recovered.get_text(0, "count")?, Some("1"));

    let tx = block_on(db.transaction())?;
    block_on(tx.query("SAVEPOINT before_duplicate"))?;
    let duplicate = block_on(tx.query_params(
        "INSERT INTO reg.accounts(login, balance) VALUES ($1, $2::numeric)",
        [QueryParam::from("alpha@example.com"), QueryParam::from("1")],
    ))
    .unwrap_err();
    assert_postgres_error(&duplicate, "23505", "duplicate key", "duplicate-key error");
    block_on(tx.query("ROLLBACK TO SAVEPOINT before_duplicate"))?;
    block_on(tx.query_params(
        "INSERT INTO reg.accounts(login, balance, active) VALUES ($1, $2::numeric, $3::bool)",
        [
            QueryParam::from("beta@example.com"),
            QueryParam::from("5"),
            QueryParam::from(false),
        ],
    ))?;
    block_on(tx.commit())?;

    let committed = block_on(db.query("SELECT count(*)::text AS count FROM reg.accounts"))?;
    assert_eq!(committed.get_text(0, "count")?, Some("2"));

    block_on(db.execute("CREATE INDEX accounts_login_idx ON reg.accounts(login)"))?;
    block_on(db.execute("SET enable_seqscan = off"))?;
    let plan =
        block_on(db.query("EXPLAIN SELECT * FROM reg.accounts WHERE login = 'beta@example.com'"))?;
    let plan_text = (0..plan.row_count())
        .filter_map(|row| plan.get_text(row, "QUERY PLAN").ok().flatten())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        plan_text.contains("Index"),
        "expected indexed plan, got:\n{plan_text}"
    );
    block_on(db.execute("RESET enable_seqscan"))?;

    let expected_error = block_on(db.query("SELECT * FROM reg.missing_relation")).unwrap_err();
    assert_postgres_error(
        &expected_error,
        "42P01",
        "missing_relation",
        "missing relation error",
    );
    let after_error = block_on(db.query("SELECT 'ready'::text AS state"))?;
    assert_eq!(after_error.get_text(0, "state")?, Some("ready"));

    run_extended_protocol_error_recovery(db)?;
    run_privileges_utility_and_lock_regression(db)?;
    run_copy_from_stdin_and_reuse(db)?;
    run_copy_from_stdin_error_recovery(db)?;
    run_copy_from_stdin_copyfail_recovery(db)?;
    run_copy_streaming_and_reuse(db)?;

    Ok(())
}

fn run_icu_collation_regression(db: &Oliphaunt) -> Result<()> {
    let available = block_on(db.query(
        "SELECT (count(*) > 0)::text AS available FROM pg_collation WHERE collprovider = 'i'",
    ))?;
    assert_eq!(available.get_text(0, "available")?, Some("true"));

    block_on(db.execute(
        r#"
        CREATE COLLATION reg.und_numeric (
            provider = icu,
            locale = 'und-u-kn-true',
            deterministic = false
        );
        "#,
    ))?;

    let provider = block_on(db.query(
        r#"
        SELECT collprovider::text AS provider
        FROM pg_collation
        WHERE collname = 'und_numeric'
          AND collnamespace = 'reg'::regnamespace
        "#,
    ))?;
    assert_eq!(provider.get_text(0, "provider")?, Some("i"));

    let ordered = block_on(db.query(
        r#"
        SELECT string_agg(value, ',' ORDER BY value COLLATE reg.und_numeric) AS values
        FROM (VALUES ('10'), ('2'), ('1')) AS input(value)
        "#,
    ))?;
    assert_eq!(ordered.get_text(0, "values")?, Some("1,2,10"));

    Ok(())
}

fn run_curated_postgres_feature_regression(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE DOMAIN reg.positive_cents AS integer CHECK (VALUE >= 0);
        CREATE TYPE reg.order_state AS ENUM ('new', 'paid', 'shipped');
        CREATE TABLE reg.customers (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email text NOT NULL UNIQUE,
            metadata jsonb NOT NULL DEFAULT '{}'::jsonb
        );
        CREATE TABLE reg.orders (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id integer NOT NULL REFERENCES reg.customers(id) ON DELETE CASCADE,
            state reg.order_state NOT NULL DEFAULT 'new',
            amount reg.positive_cents NOT NULL,
            created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            amount_bucket integer GENERATED ALWAYS AS (amount / 1000) STORED,
            UNIQUE (customer_id, id) DEFERRABLE INITIALLY IMMEDIATE
        );
        CREATE INDEX orders_paid_amount_idx ON reg.orders ((amount * 2)) WHERE state = 'paid';
        CREATE TABLE reg.events (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payload jsonb NOT NULL,
            seen_at tstzrange NOT NULL
        );
        CREATE TABLE reg.inventory (
            sku text PRIMARY KEY,
            quantity integer NOT NULL CHECK (quantity >= 0)
        );
        CREATE TABLE reg.inventory_delta (
            sku text NOT NULL REFERENCES reg.inventory(sku),
            delta integer NOT NULL
        );
        "#,
    ))?;

    block_on(db.query_params(
        "INSERT INTO reg.customers(email, metadata) VALUES ($1, $2::jsonb)",
        [
            QueryParam::from("customer@example.com"),
            QueryParam::from(r#"{"segment":"enterprise","region":"apac"}"#),
        ],
    ))?;
    block_on(db.execute(
        r#"
        INSERT INTO reg.orders(customer_id, state, amount)
        SELECT id, 'paid'::reg.order_state, amount
        FROM reg.customers
        CROSS JOIN (VALUES (1250), (4500), (9900)) AS input(amount);
        INSERT INTO reg.events(payload, seen_at)
        VALUES
            ('{"kind":"signup","score":7}'::jsonb, tstzrange(clock_timestamp(), clock_timestamp() + interval '1 hour', '[)')),
            ('{"kind":"purchase","score":11}'::jsonb, tstzrange(clock_timestamp() + interval '2 hours', clock_timestamp() + interval '3 hours', '[)'));
        INSERT INTO reg.inventory VALUES ('sku-1', 10), ('sku-2', 20);
        INSERT INTO reg.inventory_delta VALUES ('sku-1', 2), ('sku-1', -1), ('sku-2', 5);
        "#,
    ))?;

    let aggregate = block_on(db.query(
        r#"
        WITH ranked AS (
            SELECT
                c.email,
                o.amount,
                o.amount_bucket,
                row_number() OVER (PARTITION BY c.id ORDER BY o.amount DESC) AS rank
            FROM reg.customers AS c
            JOIN LATERAL (
                SELECT amount, amount_bucket FROM reg.orders
                WHERE customer_id = c.id
                ORDER BY amount DESC
                LIMIT 2
            ) AS o ON true
        )
        SELECT
            count(*)::text AS rows,
            sum(amount)::text AS total,
            string_agg(amount::text || ':' || amount_bucket::text || ':' || rank::text, ',' ORDER BY amount DESC) AS ranked
        FROM ranked
        "#,
    ))?;
    assert_eq!(aggregate.get_text(0, "rows")?, Some("2"));
    assert_eq!(aggregate.get_text(0, "total")?, Some("14400"));
    assert_eq!(aggregate.get_text(0, "ranked")?, Some("9900:9:1,4500:4:2"));

    let json_range = block_on(db.query(
        r#"
        SELECT
            payload->>'kind' AS kind,
            (payload->>'score')::int::text AS score,
            (upper(seen_at) > lower(seen_at))::text AS non_empty
        FROM reg.events
        WHERE payload @> '{"kind":"purchase"}'::jsonb
        "#,
    ))?;
    assert_eq!(json_range.get_text(0, "kind")?, Some("purchase"));
    assert_eq!(json_range.get_text(0, "score")?, Some("11"));
    assert_eq!(json_range.get_text(0, "non_empty")?, Some("true"));

    let recursive = block_on(db.query(
        r#"
        WITH RECURSIVE walk(n, factorial) AS (
            VALUES (1, 1)
            UNION ALL
            SELECT n + 1, factorial * (n + 1)
            FROM walk
            WHERE n < 6
        )
        SELECT factorial::text FROM walk ORDER BY n DESC LIMIT 1
        "#,
    ))?;
    assert_eq!(recursive.get_text(0, "factorial")?, Some("720"));

    let merge = block_on(db.query(
        r#"
        MERGE INTO reg.inventory AS target
        USING (
            SELECT sku, sum(delta) AS delta
            FROM reg.inventory_delta
            GROUP BY sku
        ) AS source
        ON target.sku = source.sku
        WHEN MATCHED THEN
            UPDATE SET quantity = target.quantity + source.delta
        RETURNING target.sku, target.quantity::text
        "#,
    ))?;
    assert_eq!(merge.row_count(), 2);
    let inventory = block_on(db.query(
        "SELECT string_agg(sku || '=' || quantity::text, ',' ORDER BY sku) AS stock FROM reg.inventory",
    ))?;
    assert_eq!(inventory.get_text(0, "stock")?, Some("sku-1=11,sku-2=25"));

    block_on(db.execute("SET enable_seqscan = off"))?;
    let plan = block_on(
        db.query("EXPLAIN SELECT * FROM reg.orders WHERE state = 'paid' AND amount * 2 = 9000"),
    )?;
    let plan_text = (0..plan.row_count())
        .filter_map(|row| plan.get_text(row, "QUERY PLAN").ok().flatten())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        plan_text.contains("orders_paid_amount_idx"),
        "expected partial expression index in plan, got:\n{plan_text}"
    );
    block_on(db.execute("RESET enable_seqscan"))?;

    let domain_error =
        block_on(db.query("INSERT INTO reg.orders(customer_id, amount) VALUES (1, -10)"))
            .unwrap_err();
    assert_postgres_error(
        &domain_error,
        "23514",
        "positive_cents",
        "domain check error",
    );
    let after_domain_error = block_on(db.query("SELECT 'post-domain-error-ready'::text AS state"))?;
    assert_eq!(
        after_domain_error.get_text(0, "state")?,
        Some("post-domain-error-ready")
    );

    let fk_error =
        block_on(db.query("INSERT INTO reg.orders(customer_id, amount) VALUES (99999, 10)"))
            .unwrap_err();
    assert_postgres_error(
        &fk_error,
        "23503",
        "orders_customer_id_fkey",
        "foreign-key delete error",
    );
    let after_fk_error = block_on(db.query("SELECT 'post-fk-error-ready'::text AS state"))?;
    assert_eq!(
        after_fk_error.get_text(0, "state")?,
        Some("post-fk-error-ready")
    );

    Ok(())
}

fn run_privileges_utility_and_lock_regression(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE ROLE reg_reader;
        CREATE FUNCTION reg.account_balance_label(reg.accounts) RETURNS text
        LANGUAGE sql
        STABLE
        AS $$
            SELECT $1.login || ':' || $1.balance::text
        $$;
        GRANT USAGE ON SCHEMA reg TO reg_reader;
        GRANT SELECT ON reg.accounts TO reg_reader;
        "#,
    ))?;

    let function_result = block_on(db.query(
        r#"
        SELECT reg.account_balance_label(a) AS label
        FROM reg.accounts AS a
        WHERE a.login = 'alpha@example.com'
        "#,
    ))?;
    assert_eq!(
        function_result.get_text(0, "label")?,
        Some("alpha@example.com:12.50")
    );

    block_on(db.execute("SET ROLE reg_reader"))?;
    let visible_as_reader = block_on(db.query("SELECT count(*)::text AS count FROM reg.accounts"))?;
    assert_eq!(visible_as_reader.get_text(0, "count")?, Some("2"));

    let privilege_error = block_on(
        db.query("INSERT INTO reg.accounts(login, balance) VALUES ('reader@example.com', 1)"),
    )
    .unwrap_err();
    assert_postgres_error(
        &privilege_error,
        "42501",
        "permission denied",
        "reader insert privilege error",
    );
    block_on(db.execute("RESET ROLE"))?;

    let after_privilege_error =
        block_on(db.query("SELECT count(*)::text AS count FROM reg.accounts"))?;
    assert_eq!(after_privilege_error.get_text(0, "count")?, Some("2"));

    block_on(db.execute("VACUUM reg.accounts"))?;
    block_on(db.execute("ANALYZE reg.accounts"))?;
    let analyzed = block_on(db.query(
        "SELECT (reltuples >= 0)::text AS analyzed FROM pg_class WHERE oid = 'reg.accounts'::regclass",
    ))?;
    assert_eq!(analyzed.get_text(0, "analyzed")?, Some("true"));

    let tx = block_on(db.transaction())?;
    block_on(tx.query("LOCK TABLE reg.accounts IN SHARE MODE"))?;
    let advisory_lock = block_on(tx.query("SELECT pg_try_advisory_lock(424242)::text AS locked"))?;
    assert_eq!(advisory_lock.get_text(0, "locked")?, Some("true"));
    let advisory_unlock =
        block_on(tx.query("SELECT pg_advisory_unlock(424242)::text AS unlocked"))?;
    assert_eq!(advisory_unlock.get_text(0, "unlocked")?, Some("true"));
    block_on(tx.commit())?;

    let after_locks = block_on(db.query("SELECT 'post-lock-ready'::text AS state"))?;
    assert_eq!(after_locks.get_text(0, "state")?, Some("post-lock-ready"));
    Ok(())
}

fn run_extended_protocol_error_recovery(db: &Oliphaunt) -> Result<()> {
    let response = block_on(db.exec_protocol_raw(extended_parse_sync_request(
        "",
        "SELECT * FROM reg.extended_missing_relation",
        &[],
    )))?;
    let tags = backend_message_tags(response.as_bytes())?;
    assert!(
        tags.contains(&b'E'),
        "extended Parse error response did not include ErrorResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "extended Parse error response did not return ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'1'),
        "extended Parse error unexpectedly returned ParseComplete: {tags:?}"
    );

    let after_parse_error = block_on(db.query("SELECT 'post-parse-error-ready'::text AS state"))?;
    assert_eq!(
        after_parse_error.get_text(0, "state")?,
        Some("post-parse-error-ready")
    );

    let prepared = block_on(db.exec_protocol_raw(extended_parse_sync_request(
        "reg_int_stmt",
        "SELECT $1::int4 AS value",
        &[23],
    )))?;
    let tags = backend_message_tags(prepared.as_bytes())?;
    assert!(
        tags.contains(&b'1'),
        "valid extended Parse did not return ParseComplete: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "valid extended Parse did not return ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'E'),
        "valid extended Parse returned ErrorResponse: {tags:?}"
    );

    let bind_error = block_on(
        db.exec_protocol_raw(extended_bind_describe_execute_sync_request(
            "reg_int_stmt",
            &[Some(b"not-an-int".as_slice())],
        )),
    )?;
    let tags = backend_message_tags(bind_error.as_bytes())?;
    assert!(
        tags.contains(&b'E'),
        "extended Bind error response did not include ErrorResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "extended Bind error response did not return ReadyForQuery: {tags:?}"
    );

    let recovered = block_on(
        db.exec_protocol_raw(extended_bind_describe_execute_sync_request(
            "reg_int_stmt",
            &[Some(b"41".as_slice())],
        )),
    )?;
    let tags = backend_message_tags(recovered.as_bytes())?;
    assert!(
        tags.contains(&b'2'),
        "extended recovery response did not include BindComplete: {tags:?}"
    );
    assert!(
        tags.contains(&b'T'),
        "extended recovery response did not include RowDescription: {tags:?}"
    );
    assert!(
        tags.contains(&b'D'),
        "extended recovery response did not include DataRow: {tags:?}"
    );
    assert!(
        tags.contains(&b'C'),
        "extended recovery response did not include CommandComplete: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "extended recovery response did not return ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'E'),
        "extended recovery response returned ErrorResponse: {tags:?}"
    );

    let after_bind_error = block_on(db.query("SELECT 'post-bind-error-ready'::text AS state"))?;
    assert_eq!(
        after_bind_error.get_text(0, "state")?,
        Some("post-bind-error-ready")
    );
    Ok(())
}

fn run_copy_from_stdin_and_reuse(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE TABLE reg.copy_in_items (
            id integer PRIMARY KEY,
            payload text NOT NULL
        )
        "#,
    ))?;

    let response = block_on(db.exec_protocol_raw(copy_from_stdin_request(
        "COPY reg.copy_in_items(id, payload) FROM STDIN WITH (FORMAT csv)",
        &[
            b"1,alpha\n".as_slice(),
            b"2,\"with,comma\"\n".as_slice(),
            b"3,\"with \"\"quote\"\"\"\n".as_slice(),
        ],
    )))?;
    let tags = backend_message_tags(response.as_bytes())?;
    assert!(
        tags.contains(&b'G'),
        "COPY FROM response did not include CopyInResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'C'),
        "COPY FROM response did not include CommandComplete: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "COPY FROM response did not include ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'E'),
        "COPY FROM response unexpectedly included ErrorResponse: {tags:?}"
    );

    let rows = block_on(db.query(
        "SELECT count(*)::text AS count, string_agg(payload, '|' ORDER BY id) AS payloads FROM reg.copy_in_items",
    ))?;
    assert_eq!(rows.get_text(0, "count")?, Some("3"));
    assert_eq!(
        rows.get_text(0, "payloads")?,
        Some("alpha|with,comma|with \"quote\"")
    );

    let after_copy = block_on(db.query("SELECT 'post-copy-from-ready'::text AS state"))?;
    assert_eq!(
        after_copy.get_text(0, "state")?,
        Some("post-copy-from-ready")
    );
    Ok(())
}

fn run_copy_from_stdin_error_recovery(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE TABLE reg.copy_in_error_items (
            id integer PRIMARY KEY,
            payload text NOT NULL
        )
        "#,
    ))?;

    let response = block_on(db.exec_protocol_raw(copy_from_stdin_request(
        "COPY reg.copy_in_error_items(id, payload) FROM STDIN WITH (FORMAT csv)",
        &[b"not-an-integer,should-error\n".as_slice()],
    )))?;
    let tags = backend_message_tags(response.as_bytes())?;
    assert!(
        tags.contains(&b'G'),
        "COPY FROM error response did not include CopyInResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'E'),
        "COPY FROM invalid input did not produce ErrorResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "COPY FROM invalid input did not return ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'C'),
        "COPY FROM invalid input unexpectedly completed successfully: {tags:?}"
    );

    let rows = block_on(db.query("SELECT count(*)::text AS count FROM reg.copy_in_error_items"))?;
    assert_eq!(rows.get_text(0, "count")?, Some("0"));

    let after_copy_error = block_on(db.query("SELECT 'post-copy-error-ready'::text AS state"))?;
    assert_eq!(
        after_copy_error.get_text(0, "state")?,
        Some("post-copy-error-ready")
    );
    Ok(())
}

fn run_copy_from_stdin_copyfail_recovery(db: &Oliphaunt) -> Result<()> {
    block_on(db.execute(
        r#"
        CREATE TABLE reg.copy_in_copyfail_items (
            id integer PRIMARY KEY,
            payload text NOT NULL
        )
        "#,
    ))?;

    let response = block_on(db.exec_protocol_raw(copy_from_stdin_copyfail_request(
        "COPY reg.copy_in_copyfail_items(id, payload) FROM STDIN WITH (FORMAT csv)",
        "liboliphaunt native regression aborted COPY",
    )))?;
    let tags = backend_message_tags(response.as_bytes())?;
    assert!(
        tags.contains(&b'G'),
        "COPY FAIL response did not include CopyInResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'E'),
        "COPY FAIL did not produce ErrorResponse: {tags:?}"
    );
    assert!(
        tags.contains(&b'Z'),
        "COPY FAIL did not return ReadyForQuery: {tags:?}"
    );
    assert!(
        !tags.contains(&b'C'),
        "COPY FAIL unexpectedly completed successfully: {tags:?}"
    );

    let rows =
        block_on(db.query("SELECT count(*)::text AS count FROM reg.copy_in_copyfail_items"))?;
    assert_eq!(rows.get_text(0, "count")?, Some("0"));

    let after_copy_fail = block_on(db.query("SELECT 'post-copy-fail-ready'::text AS state"))?;
    assert_eq!(
        after_copy_fail.get_text(0, "state")?,
        Some("post-copy-fail-ready")
    );
    Ok(())
}

fn run_copy_streaming_and_reuse(db: &Oliphaunt) -> Result<()> {
    let streamed = Arc::new(Mutex::new(Vec::new()));
    let chunk_count = Arc::new(Mutex::new(0usize));
    let streamed_for_callback = Arc::clone(&streamed);
    let chunk_count_for_callback = Arc::clone(&chunk_count);

    block_on(db.exec_protocol_raw_stream(
        ProtocolRequest::simple_query(
            "COPY (
                SELECT i, repeat('copy-stream-', 32) AS payload
                FROM generate_series(1, 2048) AS i
            ) TO STDOUT WITH (FORMAT csv)",
        )?,
        move |chunk| {
            let mut chunks = chunk_count_for_callback.lock().map_err(|_| {
                Error::Engine("native SQL regression COPY chunk counter lock poisoned".to_owned())
            })?;
            *chunks = chunks.saturating_add(1);
            streamed_for_callback
                .lock()
                .map_err(|_| {
                    Error::Engine(
                        "native SQL regression COPY stream buffer lock poisoned".to_owned(),
                    )
                })?
                .extend_from_slice(chunk);
            Ok(())
        },
    ))?;

    let streamed = streamed
        .lock()
        .map_err(|_| Error::Engine("native SQL regression COPY stream lock poisoned".to_owned()))?;
    let chunks = *chunk_count.lock().map_err(|_| {
        Error::Engine("native SQL regression COPY chunk count lock poisoned".to_owned())
    })?;
    let copy = summarize_copy_stream(&streamed)?;
    assert!(
        chunks >= 1,
        "COPY stream callback was not invoked; parsed tags: {:?}",
        copy.tags
    );
    assert!(
        copy.tags.contains(&b'H'),
        "COPY stream did not include CopyOutResponse: {:?}",
        copy.tags
    );
    assert!(
        copy.tags.contains(&b'd'),
        "COPY stream did not include CopyData: {:?}",
        copy.tags
    );
    assert!(
        copy.tags.contains(&b'C'),
        "COPY stream did not include CommandComplete: {:?}",
        copy.tags
    );
    assert!(
        copy.tags.contains(&b'Z'),
        "COPY stream did not include ReadyForQuery: {:?}",
        copy.tags
    );
    assert!(copy.copy_data_frames >= 1);
    assert_eq!(copy.copy_data_lines, 2048);
    assert!(
        copy.copy_data_bytes > 512 * 1024,
        "COPY stream carried too little data: {} bytes",
        copy.copy_data_bytes
    );
    drop(streamed);

    let after_copy = block_on(db.query("SELECT 'post-copy-ready'::text AS state"))?;
    assert_eq!(after_copy.get_text(0, "state")?, Some("post-copy-ready"));
    Ok(())
}

fn copy_from_stdin_request(sql: &str, data_frames: &[&[u8]]) -> ProtocolRequest {
    let mut bytes = ProtocolRequest::simple_query(sql)
        .expect("native SQL regression COPY SQL should be a valid simple-query frame")
        .into_bytes();
    for data in data_frames {
        push_frontend_message(&mut bytes, b'd', data);
    }
    push_frontend_message(&mut bytes, b'c', &[]);
    ProtocolRequest::new(bytes)
}

fn copy_from_stdin_copyfail_request(sql: &str, message: &str) -> ProtocolRequest {
    let mut bytes = ProtocolRequest::simple_query(sql)
        .expect("native SQL regression COPY SQL should be a valid simple-query frame")
        .into_bytes();
    let mut body = Vec::with_capacity(message.len() + 1);
    body.extend_from_slice(message.as_bytes());
    body.push(0);
    push_frontend_message(&mut bytes, b'f', &body);
    ProtocolRequest::new(bytes)
}

fn push_frontend_message(out: &mut Vec<u8>, tag: u8, body: &[u8]) {
    out.push(tag);
    out.extend_from_slice(&((body.len() + 4) as i32).to_be_bytes());
    out.extend_from_slice(body);
}

fn extended_parse_sync_request(name: &str, sql: &str, type_oids: &[i32]) -> ProtocolRequest {
    let mut bytes = Vec::new();
    let mut body = Vec::new();
    push_protocol_cstr(&mut body, name);
    push_protocol_cstr(&mut body, sql);
    push_protocol_i16(&mut body, type_oids.len() as i16);
    for oid in type_oids {
        push_protocol_i32(&mut body, *oid);
    }
    push_frontend_message(&mut bytes, b'P', &body);
    push_frontend_message(&mut bytes, b'S', &[]);
    ProtocolRequest::new(bytes)
}

fn extended_bind_describe_execute_sync_request(
    statement: &str,
    parameters: &[Option<&[u8]>],
) -> ProtocolRequest {
    let mut bytes = Vec::new();
    let mut bind = Vec::new();
    push_protocol_cstr(&mut bind, "");
    push_protocol_cstr(&mut bind, statement);
    push_protocol_i16(&mut bind, 1);
    push_protocol_i16(&mut bind, 0);
    push_protocol_i16(&mut bind, parameters.len() as i16);
    for parameter in parameters {
        match parameter {
            Some(value) => {
                push_protocol_i32(&mut bind, value.len() as i32);
                bind.extend_from_slice(value);
            }
            None => push_protocol_i32(&mut bind, -1),
        }
    }
    push_protocol_i16(&mut bind, 0);
    push_frontend_message(&mut bytes, b'B', &bind);

    let mut describe = Vec::new();
    describe.push(b'P');
    push_protocol_cstr(&mut describe, "");
    push_frontend_message(&mut bytes, b'D', &describe);

    let mut execute = Vec::new();
    push_protocol_cstr(&mut execute, "");
    push_protocol_i32(&mut execute, 0);
    push_frontend_message(&mut bytes, b'E', &execute);
    push_frontend_message(&mut bytes, b'S', &[]);
    ProtocolRequest::new(bytes)
}

fn push_protocol_cstr(out: &mut Vec<u8>, value: &str) {
    out.extend_from_slice(value.as_bytes());
    out.push(0);
}

fn push_protocol_i16(out: &mut Vec<u8>, value: i16) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn push_protocol_i32(out: &mut Vec<u8>, value: i32) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn assert_postgres_error(error: &Error, sqlstate: &str, message: &str, context: &str) {
    let Error::Postgres(postgres) = error else {
        panic!("{context} was not structured PostgreSQL error: {error}");
    };
    assert_eq!(
        postgres.sqlstate.as_deref(),
        Some(sqlstate),
        "{context} lost SQLSTATE: {postgres:?}"
    );
    assert!(
        postgres.message.contains(message)
            || postgres
                .constraint_name
                .as_deref()
                .is_some_and(|constraint| constraint.contains(message)),
        "{context} lost PostgreSQL detail: {postgres:?}"
    );
}

fn backend_message_tags(bytes: &[u8]) -> Result<Vec<u8>> {
    let mut offset = 0usize;
    let mut tags = Vec::new();
    while offset < bytes.len() {
        if bytes.len() - offset < 5 {
            return Err(Error::Engine(format!(
                "truncated backend protocol frame at offset {offset}; {} trailing byte(s)",
                bytes.len() - offset
            )));
        }
        let tag = bytes[offset];
        let len = i32::from_be_bytes([
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
            bytes[offset + 4],
        ]);
        if len < 4 {
            return Err(Error::Engine(format!(
                "invalid backend protocol frame length {len} at offset {offset}"
            )));
        }
        let frame_end = offset
            .checked_add(1 + len as usize)
            .ok_or_else(|| Error::Engine("backend protocol frame length overflow".to_owned()))?;
        if frame_end > bytes.len() {
            return Err(Error::Engine(format!(
                "truncated backend protocol body for tag {} at offset {offset}: frame ends at {frame_end}, response has {} bytes",
                tag as char,
                bytes.len()
            )));
        }
        tags.push(tag);
        offset = frame_end;
    }
    Ok(tags)
}

struct CopyStreamSummary {
    tags: Vec<u8>,
    copy_data_frames: usize,
    copy_data_bytes: usize,
    copy_data_lines: usize,
}

fn summarize_copy_stream(bytes: &[u8]) -> Result<CopyStreamSummary> {
    let mut offset = 0usize;
    let mut tags = Vec::new();
    let mut copy_data_frames = 0usize;
    let mut copy_data_bytes = 0usize;
    let mut copy_data_lines = 0usize;

    while offset < bytes.len() {
        if bytes.len() - offset < 5 {
            return Err(Error::Engine(format!(
                "truncated backend protocol frame at offset {offset}; {} trailing byte(s)",
                bytes.len() - offset
            )));
        }
        let tag = bytes[offset];
        let len = i32::from_be_bytes([
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
            bytes[offset + 4],
        ]);
        if len < 4 {
            return Err(Error::Engine(format!(
                "invalid backend protocol frame length {len} at offset {offset}"
            )));
        }
        let frame_end = offset
            .checked_add(1 + len as usize)
            .ok_or_else(|| Error::Engine("backend protocol frame length overflow".to_owned()))?;
        if frame_end > bytes.len() {
            return Err(Error::Engine(format!(
                "truncated backend protocol body for tag {} at offset {offset}: frame ends at {frame_end}, response has {} bytes",
                tag as char,
                bytes.len()
            )));
        }
        tags.push(tag);
        if tag == b'd' {
            copy_data_frames = copy_data_frames.saturating_add(1);
            let body = &bytes[offset + 5..frame_end];
            copy_data_bytes = copy_data_bytes.saturating_add(body.len());
            copy_data_lines =
                copy_data_lines.saturating_add(body.iter().filter(|byte| **byte == b'\n').count());
        }
        offset = frame_end;
    }

    Ok(CopyStreamSummary {
        tags,
        copy_data_frames,
        copy_data_bytes,
        copy_data_lines,
    })
}

fn native_runtime_env_is_unavailable() -> bool {
    std::env::var_os("LIBOLIPHAUNT_PATH").is_none()
}

fn block_on<F: Future>(future: F) -> F::Output {
    let waker = Waker::from(Arc::new(ThreadWaker(thread::current())));
    let mut context = Context::from_waker(&waker);
    let mut future = Box::pin(future);

    loop {
        match future.as_mut().poll(&mut context) {
            Poll::Ready(value) => return value,
            Poll::Pending => thread::park_timeout(Duration::from_millis(1)),
        }
    }
}

struct ThreadWaker(thread::Thread);

impl Wake for ThreadWaker {
    fn wake(self: Arc<Self>) {
        self.0.unpark();
    }

    fn wake_by_ref(self: &Arc<Self>) {
        self.0.unpark();
    }
}
