name = "icu-windows"
kind = "archive"
url = "https://github.com/unicode-org/icu/releases/download/release-76-1/icu4c-76_1-Win64-MSVC2022.zip"
branch = "release-76-1"
commit = "bedba77dd1feca09e9ae9922109a285c0ecf46d09c80b65eae6eae63a4e155dc"
sha256 = "bedba77dd1feca09e9ae9922109a285c0ecf46d09c80b65eae6eae63a4e155dc"
strip_prefix = "."
