import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const owner = import.meta.dir;
const prepared = path.resolve(
  process.argv[2] ?? path.join(owner, '../../../target/oliphaunt-wasix-postmaster/runtime/wasmer'),
);
const crates = {
  wasmer: 'api',
  'wasmer-compiler-cranelift': 'compiler-cranelift',
  'wasmer-compiler-llvm': 'compiler-llvm',
  'wasmer-types': 'types',
  'wasmer-vm': 'vm',
  'wasmer-wasix': 'wasix',
};
let config =
  '# Generated by executor/prepare-paths.mts; prepared dependency locations only.\n[patch.crates-io]\n';
for (const [name, directory] of Object.entries(crates)) {
  const location = path.join(prepared, 'lib', directory);
  if (!existsSync(path.join(location, 'Cargo.toml'))) {
    throw new Error(
      `Missing prepared ${name}: ${location}; run the postmaster Wasmer preparation first`,
    );
  }
  config += `${JSON.stringify(name)} = { path = ${JSON.stringify(location)} }\n`;
}
const cliManifest = path.join(prepared, 'lib/cli/Cargo.toml');
const cli = readFileSync(cliManifest, 'utf8');
const dependency = /^(oliphaunt-wasix-postmaster-executor = \{[^\n]*path = )"(?:[^"\\]|\\.)*"/m;
if (!dependency.test(cli))
  throw new Error(`Prepared CLI lacks the executor dependency: ${cliManifest}`);
// The patched generic CLI shares the sealed loader. Point it at its actual owner.
const ownerFromCli = path.relative(path.dirname(cliManifest), owner).split(path.sep).join('/');
writeFileSync(
  cliManifest,
  cli.replace(dependency, (_, prefix) => prefix + JSON.stringify(ownerFromCli)),
);
mkdirSync(path.join(owner, '.cargo'), { recursive: true });
writeFileSync(path.join(owner, '.cargo/config.toml'), config);
console.log(`Prepared Cargo dependency paths for ${owner}`);
