[postgresql]
version = "18.3"
url = "https://ftp.postgresql.org/pub/source/v18.3/postgresql-18.3.tar.bz2"
sha256 = "d95663fbbf3a80f81a9d98d895266bdcb74ba274bcc04ef6d76630a72dee016f"

[patches]
directory = "../patches/postgresql-18.3"
series = [
  "0001-libpglite-add-backend-host-io.patch",
  "0002-libpglite-add-embedded-entrypoint.patch",
  "0003-libpglite-return-from-embedded-frontend-terminate.patch",
  "0004-libpglite-run-embedded-exit-cleanup.patch",
  "0005-libpglite-restore-host-cwd.patch",
]
