$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  globFormat: "source-path"
  globs:
    - "moon.yml"
    - "benchmarks/moon.yml"
    - "examples/moon.yml"
    - "src/**/moon.yml"
    - "tools/**/moon.yml"
  sources:
    ci-workflows: ".github"

pipeline:
  installDependencies: false
  logRunningCommand: true

vcs:
  provider: "github"
  defaultBranch: "main"

telemetry: false

experiments:
  casOutputsCache: true
