$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  globFormat: "source-path"
  globs:
    - "**/moon.yml"
    - "!target/**"
    - "!**/node_modules/**"
  sources:
    ci-workflows: ".github"

pipeline:
  installDependencies: false
  logRunningCommand: true

cache:
  cas:
    verifyIntegrity: true

vcs:
  provider: "github"
  defaultBranch: "main"

telemetry: false

experiments:
  casOutputsCache: true
