import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { nativeComponentInventory } from './native-component-contract.mts';

type Row = Record<string, any>;
export const modelPath = 'src/extensions/tools/check-extension-model.sh';
export const catalogPath = 'src/extensions/generated/extensions.catalog.json';
export const contribPath = 'src/extensions/contrib/postgres18.toml';
const componentsPath = 'src/extensions/catalog/native-components.toml';
const externalRoot = 'src/extensions/external';
const smokeRoot = 'src/shared/fixtures/extensions';
export const readJson = (file: string): Row => JSON.parse(readFileSync(file, 'utf8'));
export const readToml = (file: string): Row => Bun.TOML.parse(readFileSync(file, 'utf8'));
export function sorted(value: any): any {
  if (Array.isArray(value)) return value.map(sorted);
  if (value !== null && typeof value === 'object')
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sorted(value[key])]),
    );
  return value;
}
export const jsonText = (value: any) => `${JSON.stringify(sorted(value), null, 2)}\n`;
const unique = (values: string[]) => [...new Set(values)].sort();
const literal = (value: any) => JSON.stringify(value);
const camel = (value: string) => value.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
const moduleStem = (row: Row): string | null =>
  (row['native-module-file'] || row['module-file'])?.replace(/\.(so|dylib|dll)$/, '') ?? null;
const generated = `// This file is generated by ${modelPath}.\n// Do not edit by hand.\n\n`;

export function extensionProjections(catalog: Row, releases: Row[]): Map<string, string> {
  const inventory = nativeComponentInventory();
  const contrib = readToml(contribPath).extensions;
  const extensions: Row[] = [...catalog.extensions].sort((a, b) =>
    a['sql-name'] < b['sql-name'] ? -1 : 1,
  );
  const names = new Set(extensions.map((row) => row['sql-name']));
  assert.equal(names.size, extensions.length, 'duplicate SQL extension name');
  const releaseByName = new Map(releases.map((row) => [row.sqlName, row]));
  assert.equal(releaseByName.size, releases.length, 'duplicate release owner');
  for (const row of inventory.resolutions)
    assert(names.has(row.extension), `unknown native component extension ${row.extension}`);
  const recipes = new Map(
    extensions.map((row) => {
      const file = `${externalRoot}/${row['sql-name']}/recipe.toml`;
      return [row['sql-name'], existsSync(file) ? readToml(file) : {}];
    }),
  );
  const resolutions = (sql: string) => inventory.resolutions.filter((row) => row.extension === sql);
  const mobile = (
    sql: string,
    field: string,
    targets = ['ios-xcframework', 'android-arm64-v8a', 'android-x86_64'],
  ) =>
    unique(
      resolutions(sql)
        .filter(
          (row) =>
            row.family === 'native' &&
            row.kind === 'native-static-registry' &&
            targets.includes(row.target),
        )
        .flatMap((row) => row[field]),
    );
  const source = (name: string, path: string) => ({ name, path });
  const metadataRows = extensions.map((extension) => {
    const sql = extension['sql-name'];
    const release = releaseByName.get(sql);
    assert(release, `no release owner for ${sql}`);
    const recipe = recipes.get(sql)!;
    const contribRow = contrib.find((row: Row) => row['sql-name'] === sql);
    const files = [...(recipe.artifacts?.data_files ?? contribRow?.['data-files'] ?? [])].sort();
    const requirements = resolutions(sql);
    const preload = unique(
      (extension.lifecycle?.['startup-config'] ?? []).flatMap((assignment: string) =>
        assignment.startsWith('shared_preload_libraries=')
          ? assignment
              .slice('shared_preload_libraries='.length)
              .split(',')
              .map((value) => value.trim())
              .filter(Boolean)
          : [],
      ),
    );
    const environment = [...(recipe.runtime_environment ?? [])]
      .map((row) => {
        for (const key of ['name', 'path', 'required_file'])
          assert(
            typeof row[key] === 'string' && row[key],
            `${sql} runtime environment requires ${key}`,
          );
        return { name: row.name, path: row.path, required_file: row.required_file };
      })
      .sort((a, b) =>
        a.name < b.name
          ? -1
          : a.name > b.name
            ? 1
            : a.path < b.path
              ? -1
              : a.path > b.path
                ? 1
                : a.required_file < b.required_file
                  ? -1
                  : 1,
      );
    return {
      id: extension.id,
      'sql-name': sql,
      'display-name': extension['display-name'] ?? extension.id,
      'postgres-major': 18,
      'artifact-product': release.artifactProduct ?? release.product,
      'release-product':
        release.versioning === 'runtime-bound'
          ? release.compatibility.nativeRuntimeProduct
          : release.product,
      'cargo-package': release.cargoPackage,
      'npm-package': release.npmPackage,
      'maven-group': release.mavenGroup,
      'maven-artifact': release.mavenArtifact,
      'runtime-bound': release.versioning === 'runtime-bound',
      'creates-extension': Boolean(extension.lifecycle?.['create-extension']),
      'native-module-stem': moduleStem(extension),
      dependencies: extension.dependencies ?? [],
      'selected-extension-dependencies': (extension.dependencies ?? [])
        .filter((name: string) => names.has(name))
        .sort(),
      'native-components': unique(requirements.flatMap((row) => row.components)),
      'native-component-requirements': requirements.map((row) => ({
        family: row.family,
        kind: row.kind,
        target: row.target,
        components: row.components,
        'link-units': row.linkUnits,
        'runtime-files': row.runtimeFiles,
      })),
      'shared-preload-libraries': preload,
      'data-files': files,
      'runtime-share-data-files': files
        .map((file: string) => file.replace(/^share\/postgresql\//, ''))
        .sort(),
      'extension-sql-file-prefixes': [
        ...(recipe.artifacts?.extension_sql_file_prefixes ?? []),
      ].sort(),
      'extension-sql-file-names': [...(recipe.artifacts?.extension_sql_file_names ?? [])].sort(),
      'runtime-environment': environment,
      'source-kind': extension['source-kind'],
    };
  });
  const hash = createHash('sha256')
    .update(JSON.stringify(sorted(metadataRows)))
    .digest('hex');
  const outputs = new Map<string, string>();
  const putJson = (file: string, value: any) => outputs.set(file, jsonText(value));
  const base = 'src/extensions/generated';
  putJson(`${base}/sdk/extensions.json`, {
    'format-version': 1,
    'extension-catalog-sha256': hash,
    'generated-from': [
      source('extension-catalog', catalogPath),
      source('native-components', componentsPath),
      source('extension-recipes', 'src/extensions'),
      source('release-products', 'src'),
    ],
    extensions: metadataRows,
  });
  const ios = new Map(
    extensions.map((row) => [
      row['sql-name'],
      mobile(row['sql-name'], 'linkUnits', ['ios-xcframework']),
    ]),
  );
  putJson(`${base}/sdk/ios-static-dependencies.json`, {
    'format-version': 1,
    'generated-from': [
      source('extension-catalog', catalogPath),
      source('native-components', componentsPath),
      source('contrib-recipe', contribPath),
      source('external-static-targets', externalRoot),
    ],
    extensions: [...ios]
      .filter(([, deps]) => deps.length)
      .map(([sql, deps]) => ({ 'sql-name': sql, 'static-dependencies': deps })),
  });
  const tsFields = [
    'id',
    'sql-name',
    'display-name',
    'postgres-major',
    'artifact-product',
    'release-product',
    'cargo-package',
    'npm-package',
    'maven-group',
    'maven-artifact',
    'runtime-bound',
    'creates-extension',
    'native-module-stem',
    'dependencies',
    'selected-extension-dependencies',
    'shared-preload-libraries',
    'data-files',
    'runtime-share-data-files',
    'extension-sql-file-prefixes',
    'extension-sql-file-names',
    'source-kind',
  ];
  for (const [sdk, includeIos] of [
    ['js', false],
    ['react-native', true],
  ] as const) {
    const fields = [...tsFields];
    if (includeIos) fields.splice(15, 0, 'ios-static-dependencies');
    const rows = metadataRows.map((row) =>
      Object.fromEntries(
        fields.map((field) => [
          camel(field),
          field === 'ios-static-dependencies' ? ios.get(row['sql-name']) : row[field],
        ]),
      ),
    );
    const type = fields
      .map((field) => {
        const value = rows[0][camel(field)];
        return `  readonly ${camel(field)}: ${field === 'native-module-stem' ? 'string | null' : Array.isArray(value) ? 'readonly string[]' : typeof value};`;
      })
      .join('\n');
    outputs.set(
      `src/sdks/${sdk}/src/generated/extensions.ts`,
      `${generated}export type GeneratedExtensionMetadata = {\n${type}\n};\n\nexport const GENERATED_EXTENSION_METADATA_SHA256 = ${literal(hash)} as const;\n\nexport const GENERATED_EXTENSION_METADATA = ${JSON.stringify(sorted(rows), null, 2)} as const satisfies readonly GeneratedExtensionMetadata[];\n\nexport function generatedExtensionBySqlName(sqlName: string): GeneratedExtensionMetadata | undefined {\n  return GENERATED_EXTENSION_METADATA.find((extension) => extension.sqlName === sqlName);\n}\n\nexport function generatedSharedPreloadLibraries(extensionSqlNames: readonly string[]): string[] {\n  const libraries = new Set<string>();\n  for (const sqlName of extensionSqlNames) {\n    const extension = generatedExtensionBySqlName(sqlName);\n    for (const library of extension?.sharedPreloadLibraries ?? []) {\n      libraries.add(library);\n    }\n  }\n  return [...libraries].sort();\n}\n`,
    );
  }
  const smokePlan = metadataRows.map((row) => ({
    sqlName: row['sql-name'],
    createsExtension: row['creates-extension'],
    selectedExtensionDependencies: row['selected-extension-dependencies'],
  }));
  const smoke = Object.fromEntries(
    metadataRows.map((row) => [
      row['sql-name'],
      readFileSync(`${smokeRoot}/${row['sql-name']}.sql`, 'utf8')
        .split('-- oliphaunt-statement')
        .map((sql) => sql.trim())
        .filter(Boolean),
    ]),
  );
  for (const [name, statements] of Object.entries(smoke))
    assert(statements.length, `empty smoke recipe for ${name}`);
  outputs.set(
    'examples/react-native-expo/src/generated/extension-smoke.ts',
    `// This file is generated by ${modelPath}.\n// Do not edit by hand. It belongs only to installed mobile qualification.\n\nexport type GeneratedMobileExtensionProof = {\n  readonly sqlName: string;\n  readonly createsExtension: boolean;\n  readonly selectedExtensionDependencies: readonly string[];\n};\n\nexport const GENERATED_MOBILE_EXTENSION_METADATA_SHA256 = ${literal(hash)} as const;\n\nexport const GENERATED_MOBILE_EXTENSION_PLAN = ${JSON.stringify(smokePlan, null, 2)} as const satisfies readonly GeneratedMobileExtensionProof[];\n\nexport const GENERATED_MOBILE_EXTENSION_SMOKE = ${JSON.stringify(sorted(smoke), null, 2).replace(/[\u007f-\uffff]/g, (character) => `\\u${character.charCodeAt(0).toString(16).padStart(4, '0')}`)} as const satisfies Readonly<Record<string, readonly string[]>>;\n`,
  );
  outputs.set(
    'src/sdks/kotlin/oliphaunt/src/commonMain/kotlin/dev/oliphaunt/GeneratedExtensions.kt',
    `${generated}package dev.oliphaunt\n\ninternal data class GeneratedExtensionRuntimeContract(\n    val createsExtension: Boolean,\n    val nativeModuleStem: String?,\n)\n\ninternal val generatedExtensionRuntimeContracts: Map<String, GeneratedExtensionRuntimeContract> = mapOf(\n${metadataRows.map((row) => `    ${literal(row['sql-name'])} to GeneratedExtensionRuntimeContract(createsExtension = ${row['creates-extension']}, nativeModuleStem = ${literal(row['native-module-stem'])}),`).join('\n')}\n)\n\ninternal val generatedExtensionSqlNames: Set<String> = generatedExtensionRuntimeContracts.keys\n\ninternal fun generatedExtensionSqlNameExists(sqlName: String): Boolean = generatedExtensionSqlNames.contains(sqlName)\n\ninternal fun generatedExtensionRuntimeContract(sqlName: String): GeneratedExtensionRuntimeContract? = generatedExtensionRuntimeContracts[sqlName]\n`,
  );
  outputs.set(
    'src/sdks/kotlin/oliphaunt-android-gradle-plugin/src/main/resources/dev/oliphaunt/android/extensions.properties',
    [
      `# This file is generated by ${modelPath}.`,
      '# Do not edit by hand.',
      'schema=oliphaunt-android-extension-catalog-v2',
      `catalogSha256=${hash}`,
      ...metadataRows.flatMap((row) =>
        Object.entries({
          artifactProduct: row['artifact-product'],
          releaseProduct: row['release-product'],
          mavenGroup: row['maven-group'],
          mavenArtifact: row['maven-artifact'],
          runtimeBound: row['runtime-bound'],
          dependencies: row['selected-extension-dependencies'].join(','),
        }).map(([key, value]) => `extension.${row['sql-name']}.${key}=${value}`),
      ),
      '',
    ].join('\n'),
  );
  outputs.set(
    'src/sdks/rust/src/generated/extensions.rs',
    rustModule(
      metadataRows.map((row) => ({
        ...row,
        'rust-constant': extensions.find((extension) => extension.id === row.id)!['rust-constant'],
      })),
    ),
  );
  const modules = metadataRows
    .filter((row) => row['native-module-stem'] !== null)
    .map((row) => ({
      id: row.id,
      'sql-name': row['sql-name'],
      'native-module-stem': row['native-module-stem'],
      'data-files': row['data-files'],
      'static-registry-required': true,
    }));
  putJson(`${base}/mobile/static-registry.json`, {
    'format-version': 1,
    'generated-from': [
      source('extension-catalog', catalogPath),
      source('extension-definitions', externalRoot),
    ],
    modules,
  });
  const mobileRows = modules.map((module) => {
    const sql = module['sql-name'];
    const extension = extensions.find((row) => row['sql-name'] === sql)!;
    const contribRow = contrib.find((row: Row) => row['sql-name'] === sql);
    const targetFile = `${externalRoot}/${sql}/targets/native-static-registry.toml`;
    const target = existsSync(targetFile) ? readToml(targetFile) : {};
    const list = (field: string, contribField?: string) =>
      unique(target[field]?.length ? target[field] : (contribRow?.[contribField!] ?? []));
    const sourceRel =
      extension['source-kind'] === 'postgres-contrib'
        ? `contrib/${contribRow?.['contrib-dir']}`
        : extension['control-file']?.match(/^(target\/oliphaunt-sources\/checkouts\/[^/]+)\//)?.[1];
    assert(sourceRel && !sourceRel.endsWith('undefined'), `${sql} has no mobile source path`);
    const dependencies = (field: string, targets?: string[]) => mobile(sql, field, targets);
    return [
      sql,
      module['native-module-stem'],
      contribRow ? 'contrib' : 'external',
      sourceRel,
      dependencies('linkUnits'),
      dependencies('linkUnits', ['ios-xcframework']),
      dependencies('linkUnits', ['android-arm64-v8a', 'android-x86_64']),
      dependencies('sources'),
      list('include_dirs', 'mobile-static-include-dirs'),
      list('cflags', 'mobile-static-cflags').map((flag) =>
        flag.replaceAll('@EXTVERSION@', extension.control?.['default-version'] ?? ''),
      ),
      dependencies('sources'),
      dependencies('sources', ['ios-xcframework']),
      dependencies('sources', ['android-arm64-v8a', 'android-x86_64']),
      list('hash_dirs', 'mobile-static-hash-dirs'),
      list('source_files'),
      list('source_recursive_dirs'),
    ]
      .map((value) => (Array.isArray(value) ? value.join(',') : value))
      .join('\t')
      .replace(/\t+$/, '');
  });
  outputs.set(
    `${base}/mobile/static-extensions.tsv`,
    [
      `# @generated by ${modelPath} --write`,
      'sql-name\tnative-module-stem\tsource-kind\tsource-rel\tmobile-static-dependencies\tios-static-dependencies\tandroid-static-dependencies\tinclude-dependencies\tinclude-dirs\tcflags\thash-source-dependencies\tios-hash-source-dependencies\tandroid-hash-source-dependencies\thash-dirs\tsource-files\tsource-recursive-dirs',
      ...mobileRows,
      '',
    ].join('\n'),
  );
  putJson(`${base}/wasix/extensions.json`, {
    'format-version': 1,
    'generated-from': [
      source('extension-catalog', catalogPath),
      source('native-components', componentsPath),
      source('extension-definitions', externalRoot),
    ],
    extensions: extensions.map((row) => {
      const sql = row['sql-name'];
      const closure = resolutions(sql).find(
        (row) =>
          row.family === 'wasix' && row.kind === 'wasix-runtime' && row.target === 'wasix-portable',
      );
      const targetFile = `${externalRoot}/${sql}/targets/wasix.toml`;
      const support = existsSync(targetFile)
        ? (readToml(targetFile).native_support_modules ?? [])
        : [];
      return {
        id: row.id,
        'sql-name': sql,
        archive: row.archive || `extensions/${sql}.tar.zst`,
        'native-module-file': row['native-module-file'] || row['module-file'] || null,
        'native-support-modules': support
          .map((module: Row) =>
            Object.fromEntries(
              ['name', 'runtime_path', 'build_path', 'aot_file'].map((field) => {
                assert(
                  typeof module[field] === 'string' && module[field],
                  `${sql} support module needs ${field}`,
                );
                return [field.replaceAll('_', '-'), module[field]];
              }),
            ),
          )
          .sort((a: Row, b: Row) => (a.name < b.name ? -1 : 1)),
        'native-components': closure?.components ?? [],
        'native-link-units': closure?.linkUnits ?? [],
        'native-runtime-files': closure?.runtimeFiles ?? [],
        dependencies: row.dependencies ?? [],
        'load-order': row['load-order'] ?? [],
        lifecycle: row.lifecycle ?? {},
      };
    }),
  });
  return outputs;
}

function rustModule(rows: Row[]): string {
  const variant = (row: Row) =>
    row['rust-constant']
      .split('_')
      .map((part: string) => part[0] + part.slice(1).toLowerCase())
      .join('');
  const id = (row: Row) => `ExtensionId::${variant(row)}`;
  const selected = (row: Row) => `Extension::${row['rust-constant']}`;
  const option = (value: string | null) => (value === null ? 'None' : `Some(${literal(value)})`);
  const array = (values: string[]) => `&[${values.join(', ')}]`;
  const match = (name: string, type: string, value: (row: Row) => string) =>
    `/// Generated extension metadata accessor.\npub(super) const fn ${name}(extension: Extension) -> ${type} {\n    match extension.id {\n${rows.map((row) => `        ${id(row)} => ${value(row)},`).join('\n')}\n    }\n}\n`;
  for (const row of rows) {
    assert(
      /^[A-Z][A-Z0-9_]*$/.test(row['rust-constant']),
      `invalid Rust extension constant ${row.id}`,
    );
    assert(
      row['shared-preload-libraries'].length <= 1,
      `Rust Extension supports one preload library: ${row.id}`,
    );
  }
  return [
    `// @generated by ${modelPath} --write`,
    '// Do not edit by hand.',
    '',
    'use super::ExtensionRuntimeEnvironment;',
    '',
    '/// Native PostgreSQL 18 extension artifact that can be selected by an app.',
    '#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]',
    'pub struct Extension {',
    '    id: ExtensionId,',
    '}',
    '',
    '#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]',
    'enum ExtensionId {',
    ...rows.map((row) => `    /// PostgreSQL \`${row['sql-name']}\`.\n    ${variant(row)},`),
    '}',
    '',
    'impl Extension {',
    ...rows.map(
      (row) =>
        `    /// Select the \`${row['sql-name']}\` artifact.\n    pub const ${row['rust-constant']}: Self = Self { id: ${id(row)} };`,
    ),
    '',
    '    /// All PostgreSQL 18 extension artifacts known to the native SDK.',
    `    pub const ALL: &'static [Self] = ${array(rows.map(selected))};`,
    '}',
    '',
    match('sql_name', "&'static str", (row) => literal(row['sql-name'])),
    match('native_module_stem', "Option<&'static str>", (row) => option(row['native-module-stem'])),
    match('creates_extension', 'bool', (row) => String(row['creates-extension'])),
    match('dependencies', "&'static [Extension]", (row) =>
      array(
        row['selected-extension-dependencies'].map((sql: string) =>
          selected(rows.find((row) => row['sql-name'] === sql)!),
        ),
      ),
    ),
    match('required_shared_preload_library', "Option<&'static str>", (row) =>
      option(row['shared-preload-libraries'][0] ?? null),
    ),
    ...[
      ['extension_data_files', 'runtime-share-data-files'],
      ['extension_sql_file_prefixes', 'extension-sql-file-prefixes'],
      ['extension_sql_file_names', 'extension-sql-file-names'],
    ].map(([name, field]) =>
      match(name, "&'static [&'static str]", (row) => array(row[field].map(literal))),
    ),
    match('runtime_environment', "&'static [ExtensionRuntimeEnvironment]", (row) =>
      array(
        row['runtime-environment'].map(
          (env: Row) =>
            `ExtensionRuntimeEnvironment { name: ${literal(env.name)}, relative_path: ${literal(env.path)}, required_file: ${literal(env.required_file)} }`,
        ),
      ),
    ),
  ].join('\n');
}

export function discoverCatalog(): Row {
  const catalog = readJson('src/extensions/catalog/extensions.source.json');
  assert.equal(catalog['format-version'], 1);
  const versions = new Map<string, string>();
  const addVersion = (sql: string, version: unknown) => {
    assert(
      typeof version === 'string' &&
        /^[a-zA-Z0-9._-]{1,128}$/.test(version) &&
        !version.includes('--'),
      `invalid default version for ${sql}`,
    );
    assert(!versions.has(sql), `duplicate default version for ${sql}`);
    versions.set(sql, version);
  };
  const contrib = readToml(contribPath).extensions;
  for (const row of contrib)
    if (row['default-version'] !== undefined) addVersion(row['sql-name'], row['default-version']);
  for (const file of new Bun.Glob(`${externalRoot}/*/source.toml`).scanSync({ onlyFiles: true })) {
    const source = readToml(file),
      control = source['extension-control'];
    if (!control) continue;
    addVersion(control['sql-name'], control['default-version']);
    assert.equal(
      catalog.extensions.find((row: Row) => row['sql-name'] === control['sql-name'])?.[
        'control-file'
      ],
      `target/oliphaunt-sources/checkouts/${source.name}/${control['source-path']}`,
      `source control provenance differs: ${file}`,
    );
  }
  const ids = new Set<string>(),
    sqlNames = new Set<string>();
  for (const row of catalog.extensions) {
    assert(
      /^[a-z][a-z0-9_]*$/.test(row.id) && /^[a-z][a-z0-9_-]*$/.test(row['sql-name']),
      'invalid extension name',
    );
    assert(!ids.has(row.id) && !sqlNames.has(row['sql-name']), `duplicate extension ${row.id}`);
    ids.add(row.id);
    sqlNames.add(row['sql-name']);
    const version = versions.get(row['sql-name']);
    if (row.lifecycle['create-extension']) {
      assert(row.control && version, `missing control version for ${row.id}`);
      // Preserve the catalog's public field order while replacing source-owned versions.
      delete row.control['default-version'];
      row.control = { 'default-version': version, ...row.control };
    } else assert(!version, `module-only extension ${row.id} declares a SQL version`);
    assert(
      row.lifecycle['create-extension'] || row.lifecycle['load-sql'].length,
      `missing activation for ${row.id}`,
    );
    const recipe = contrib.find((contrib: Row) => contrib.id === row.id);
    if (recipe) {
      assert.equal(recipe['sql-name'], row['sql-name']);
      assert.equal(recipe['module-file'], row['native-module-file']);
    }
  }
  for (const sql of versions.keys())
    assert(sqlNames.has(sql), `version declared for unknown extension ${sql}`);
  for (const row of catalog.extensions)
    for (const dependency of row.dependencies)
      assert(
        dependency === 'plpgsql' || sqlNames.has(dependency) || ids.has(dependency),
        `unknown extension dependency ${dependency}`,
      );
  return {
    'format-version': 1,
    'generated-from': [
      { name: 'postgres18-source', path: 'src/postgres/versions/18/source.toml' },
      { name: 'extension-catalog', path: 'src/extensions/catalog/extensions.source.json' },
      { name: 'postgres-contrib', path: contribPath },
      { name: 'external-extension-recipes', path: externalRoot },
    ],
    extensions: catalog.extensions.sort((a: Row, b: Row) => (a.id < b.id ? -1 : 1)),
  };
}

export function catalogProjections(catalog: Row): Map<string, string> {
  const outputs = new Map([[catalogPath, `${JSON.stringify(catalog, null, 2)}\n`]]);
  const contrib = ['# id\tsql_name\tcontrib_dir\tmodule_file\tarchive'];
  const pgxs = ['# id\tsql_name\tsource_dir\tmodule_file\tarchive\tmake_args'];
  const recipes = readToml(contribPath).extensions;
  for (const row of [...catalog.extensions].sort((a, b) =>
    a['sql-name'] < b['sql-name'] ? -1 : 1,
  )) {
    const archive = `extensions/${row['sql-name']}.tar.zst`;
    if (row['source-kind'] === 'postgres-contrib') {
      const recipe = recipes.find((recipe: Row) => recipe.id === row.id);
      assert(recipe?.['contrib-dir'], `missing contrib directory ${row.id}`);
      contrib.push(
        [
          row.id,
          row['sql-name'],
          recipe['contrib-dir'],
          row['native-module-file'] ?? '-',
          archive,
        ].join('\t'),
      );
    } else if (row['source-kind'] === 'oliphaunt-other-extension') {
      const source = readToml(`${externalRoot}/${row['sql-name']}/source.toml`);
      pgxs.push(
        [
          row.id,
          row['sql-name'],
          `target/oliphaunt-sources/checkouts/${source.name}`,
          row['native-module-file'] ?? '-',
          archive,
          row.id === 'age' ? 'SIZEOF_DATUM=4' : '-',
        ].join('\t'),
      );
    } else assert.equal(row['source-kind'], 'postgis', 'unsupported extension build kind');
  }
  outputs.set('src/extensions/generated/contrib-build.tsv', `${contrib.join('\n')}\n`);
  outputs.set('src/extensions/generated/pgxs-build.tsv', `${pgxs.join('\n')}\n`);
  outputs.set(
    'src/bindings/wasix-rust/crates/oliphaunt-wasix/src/oliphaunt/generated_extensions.rs',
    wasixRustModule(catalog.extensions),
  );
  return outputs;
}

function wasixRustModule(rows: Row[]): string {
  const feature = (row: Row) => `extension-${row['sql-name'].replaceAll('_', '-')}`;
  const cfg = (row: Row) => `#[cfg(feature = ${literal(feature(row))})]`;
  const array = (values: string[]) => `&[${values.map(literal).join(', ')}]`;
  const option = (value: string | undefined) =>
    value === undefined ? 'None' : `Some(${literal(value)})`;
  const quoteSql = (value: string) => `"${value.replaceAll('"', '""')}"`;
  let text = `// @generated by ${modelPath} --write\n\nuse super::Extension;\n\n`;
  for (const row of rows) {
    const file = `${externalRoot}/${row['sql-name']}/targets/wasix.toml`;
    const target = existsSync(file) ? readToml(file) : {};
    const modules = [...(target.native_support_modules ?? [])]
      .sort((a, b) => (a.name < b.name ? -1 : 1))
      .map(
        (module) =>
          `super::ExtensionNativeModule { runtime_path: ${literal(module.runtime_path)}, aot_name: Some(${literal(`extension:${row['sql-name']}:${module.name}`)}) }`,
      );
    text += `${cfg(row)}\nconst DEFINITION_${row['rust-constant']}: Extension = Extension {\n    sql_name: ${literal(row['sql-name'])},\n    native_support_modules: &[${modules.join(', ')}],\n    native_module_file: ${option(row['native-module-file'])},\n    aot_name: ${option(row['native-module-file'] ? `extension:${row['sql-name']}` : undefined)},\n    dependencies: ${array(row.dependencies.filter((sql: string) => sql !== 'plpgsql'))},\n    startup_config: ${array(row.lifecycle['startup-config'])},\n};\n\n`;
  }
  text += `impl Extension {\n${rows.map((row) => `    /// Select the \`${row['sql-name']}\` artifact.\n    ${cfg(row)}\n    pub const ${row['rust-constant']}: Self = DEFINITION_${row['rust-constant']};`).join('\n')}\n\n    /// Extension artifacts enabled in this Cargo build.\n    pub const ALL: &'static [Self] = &[\n${rows.map((row) => `        ${cfg(row)}\n        Self::${row['rust-constant']},`).join('\n')}\n    ];\n}\n`;
  text += `\n#[cfg(test)]\npub(super) fn creates_database_object_for_test(extension: Extension) -> bool {\n    match extension.sql_name() {\n${rows.map((row) => `        ${cfg(row)}\n        ${literal(row['sql-name'])} => ${row.lifecycle['create-extension']},`).join('\n')}\n        _ => false,\n    }\n}\n`;
  const activation = (row: Row) => {
    const sql: string[] = [],
      lifecycle = row.lifecycle,
      schema = lifecycle['create-schema'];
    if (lifecycle['create-extension']) {
      if (schema && schema !== 'pg_catalog')
        sql.push(`CREATE SCHEMA IF NOT EXISTS ${quoteSql(schema)};`);
      sql.push(
        `CREATE EXTENSION IF NOT EXISTS ${quoteSql(row['sql-name'])}${schema ? ` WITH SCHEMA ${quoteSql(schema)}` : ''};`,
      );
    }
    return [...sql, ...lifecycle['load-sql'], ...lifecycle['post-create-sql']];
  };
  return (
    text +
    `\n#[cfg(test)]\npub(super) fn activation_sql_for_test(extension: Extension) -> &'static [&'static str] {\n    match extension.sql_name() {\n${rows.map((row) => `        ${cfg(row)}\n        ${literal(row['sql-name'])} => ${array(activation(row))},`).join('\n')}\n        _ => &[],\n    }\n}\n`
  );
}
