// This file is generated by src/extensions/tools/check-extension-model.py.
// Do not edit by hand.

package dev.oliphaunt

internal val generatedExtensionSqlNames: Set<String> = setOf(
    "amcheck",
    "auto_explain",
    "bloom",
    "btree_gin",
    "btree_gist",
    "citext",
    "cube",
    "dict_int",
    "dict_xsyn",
    "earthdistance",
    "file_fdw",
    "fuzzystrmatch",
    "hstore",
    "intarray",
    "isn",
    "lo",
    "ltree",
    "pageinspect",
    "pg_buffercache",
    "pg_freespacemap",
    "pg_hashids",
    "pg_ivm",
    "pg_surgery",
    "pg_textsearch",
    "pg_trgm",
    "pg_uuidv7",
    "pg_visibility",
    "pg_walinspect",
    "pgcrypto",
    "pgtap",
    "postgis",
    "seg",
    "tablefunc",
    "tcn",
    "tsm_system_rows",
    "tsm_system_time",
    "unaccent",
    "uuid-ossp",
    "vector",
)

internal fun generatedExtensionSqlNameExists(sqlName: String): Boolean = generatedExtensionSqlNames.contains(sqlName)
