// This file is generated by src/extensions/tools/check-extension-model.mjs.
// Do not edit by hand.

package dev.oliphaunt

internal data class GeneratedExtensionRuntimeContract(
    val createsExtension: Boolean,
    val nativeModuleStem: String?,
)

internal val generatedExtensionRuntimeContracts: Map<String, GeneratedExtensionRuntimeContract> = mapOf(
    "amcheck" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "amcheck"),
    "auto_explain" to GeneratedExtensionRuntimeContract(createsExtension = false, nativeModuleStem = "auto_explain"),
    "bloom" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "bloom"),
    "btree_gin" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "btree_gin"),
    "btree_gist" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "btree_gist"),
    "citext" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "citext"),
    "cube" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "cube"),
    "dict_int" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "dict_int"),
    "dict_xsyn" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "dict_xsyn"),
    "earthdistance" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "earthdistance"),
    "file_fdw" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "file_fdw"),
    "fuzzystrmatch" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "fuzzystrmatch"),
    "hstore" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "hstore"),
    "intarray" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "_int"),
    "isn" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "isn"),
    "lo" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "lo"),
    "ltree" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "ltree"),
    "pageinspect" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pageinspect"),
    "pg_buffercache" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_buffercache"),
    "pg_freespacemap" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_freespacemap"),
    "pg_hashids" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_hashids"),
    "pg_ivm" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_ivm"),
    "pg_surgery" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_surgery"),
    "pg_textsearch" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_textsearch"),
    "pg_trgm" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_trgm"),
    "pg_uuidv7" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_uuidv7"),
    "pg_visibility" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_visibility"),
    "pg_walinspect" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pg_walinspect"),
    "pgcrypto" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "pgcrypto"),
    "pgtap" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = null),
    "postgis" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "postgis-3"),
    "seg" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "seg"),
    "tablefunc" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "tablefunc"),
    "tcn" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "tcn"),
    "tsm_system_rows" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "tsm_system_rows"),
    "tsm_system_time" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "tsm_system_time"),
    "unaccent" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "unaccent"),
    "uuid-ossp" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "uuid-ossp"),
    "vector" to GeneratedExtensionRuntimeContract(createsExtension = true, nativeModuleStem = "vector"),
)

internal val generatedExtensionSqlNames: Set<String> = generatedExtensionRuntimeContracts.keys

internal fun generatedExtensionSqlNameExists(sqlName: String): Boolean = generatedExtensionSqlNames.contains(sqlName)

internal fun generatedExtensionRuntimeContract(sqlName: String): GeneratedExtensionRuntimeContract? = generatedExtensionRuntimeContracts[sqlName]
