// This file is generated by src/extensions/tools/check-extension-model.sh.
// Do not edit by hand.

package dev.oliphaunt

/** Selecting an extension exposes its linked resources; installation remains application SQL. */
public enum class OliphauntExtension(public val sqlName: String) {
    AMCHECK("amcheck"),
    AUTO_EXPLAIN("auto_explain"),
    BLOOM("bloom"),
    BTREE_GIN("btree_gin"),
    BTREE_GIST("btree_gist"),
    CITEXT("citext"),
    CUBE("cube"),
    DICT_INT("dict_int"),
    DICT_XSYN("dict_xsyn"),
    EARTHDISTANCE("earthdistance"),
    FILE_FDW("file_fdw"),
    FUZZYSTRMATCH("fuzzystrmatch"),
    HSTORE("hstore"),
    INTARRAY("intarray"),
    ISN("isn"),
    LO("lo"),
    LTREE("ltree"),
    PAGEINSPECT("pageinspect"),
    PG_BUFFERCACHE("pg_buffercache"),
    PG_FREESPACEMAP("pg_freespacemap"),
    PG_HASHIDS("pg_hashids"),
    PG_IVM("pg_ivm"),
    PG_SURGERY("pg_surgery"),
    PG_TEXTSEARCH("pg_textsearch"),
    PG_TRGM("pg_trgm"),
    PG_UUIDV7("pg_uuidv7"),
    PG_VISIBILITY("pg_visibility"),
    PG_WALINSPECT("pg_walinspect"),
    PGCRYPTO("pgcrypto"),
    PGTAP("pgtap"),
    POSTGIS("postgis"),
    SEG("seg"),
    TABLEFUNC("tablefunc"),
    TCN("tcn"),
    TSM_SYSTEM_ROWS("tsm_system_rows"),
    TSM_SYSTEM_TIME("tsm_system_time"),
    UNACCENT("unaccent"),
    UUID_OSSP("uuid-ossp"),
    VECTOR("vector"),
    ;

    public companion object {
        public fun fromSqlName(sqlName: String): OliphauntExtension = entries.firstOrNull { it.sqlName == sqlName }
            ?: throw OliphauntException("unknown Oliphaunt extension: $sqlName")
    }
}
