// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(OliphauntNativeBindingsFFI)
import OliphauntNativeBindingsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_oliphaunt_mobile_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_oliphaunt_mobile_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOliphauntMobileBindingsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol NativeBrokerWorkerProtocol: AnyObject, Sendable {
    
    func cancelRequest(generation: Data, request: UInt64) throws 
    
    func close(generation: Data) throws 
    
    func generation()  -> Data
    
    func `open`(options: OpenOptions) async throws  -> BrokerReady
    
    func restore(libraryPath: String?, destination: String) async throws 
    
    func retire() 
    
    func serve() async throws 
    
}
open class NativeBrokerWorker: NativeBrokerWorkerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_clone_nativebrokerworker(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_free_nativebrokerworker(handle, $0) }
    }

    
    /**
     * Only the verified dedicated extension/service installs process retirement.
     */
public static func create(fd: Int32, retirement: BrokerRetirement, startupTimeoutMs: UInt64)throws  -> NativeBrokerWorker  {
    return try  FfiConverterTypeNativeBrokerWorker_lift(try rustCallWithError(FfiConverterTypeNativeError_lift) {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_constructor_nativebrokerworker_create(
        FfiConverterInt32.lower(fd),
        FfiConverterCallbackInterfaceBrokerRetirement_lower(retirement),
        FfiConverterUInt64.lower(startupTimeoutMs),uniffiCallStatus
    )
})
}
    

    
open func cancelRequest(generation: Data, request: UInt64)throws   {try rustCallWithError(FfiConverterTypeNativeError_lift) {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_cancel_request(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(generation),
        FfiConverterUInt64.lower(request),uniffiCallStatus
    )
}
}
    
open func close(generation: Data)throws   {try rustCallWithError(FfiConverterTypeNativeError_lift) {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_close(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(generation),uniffiCallStatus
    )
}
}
    
open func generation() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_generation(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func `open`(options: OpenOptions)async throws  -> BrokerReady  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_open(
                        self.uniffiCloneHandle(),FfiConverterTypeOpenOptions_lower(options)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_rust_buffer,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_rust_buffer,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeBrokerReady_lift,
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func restore(libraryPath: String?, destination: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_restore(
                        self.uniffiCloneHandle(),FfiConverterOptionString.lower(libraryPath),FfiConverterString.lower(destination)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func retire()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_retire(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func serve()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativebrokerworker_serve(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeBrokerWorker: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NativeBrokerWorker

    public static func lift(_ handle: UInt64) throws -> NativeBrokerWorker {
        return NativeBrokerWorker(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NativeBrokerWorker) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeBrokerWorker {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NativeBrokerWorker, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeBrokerWorker_lift(_ handle: UInt64) throws -> NativeBrokerWorker {
    return try FfiConverterTypeNativeBrokerWorker.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeBrokerWorker_lower(_ value: NativeBrokerWorker) -> UInt64 {
    return FfiConverterTypeNativeBrokerWorker.lower(value)
}






public protocol NativeDatabaseProtocol: AnyObject, Sendable {
    
    func cancel() async throws 
    
    func detach() async throws 
    
    func request()  -> NativeRequest
    
    func brokerBeginClose() 
    
    func brokerInterrupted() 
    
    func brokerIsUsable()  -> Bool
    
    func brokerOperationBudget(remainingMs: UInt64?) 
    
}
open class NativeDatabase: NativeDatabaseProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_clone_nativedatabase(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_free_nativedatabase(handle, $0) }
    }

    
public static func `open`(options: OpenOptions)async throws  -> NativeDatabase  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_constructor_nativedatabase_open(FfiConverterTypeOpenOptions_lower(options)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_u64,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_u64,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_u64,
            liftFunc: FfiConverterTypeNativeDatabase_lift,
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
    /**
     * The adapter retains its descriptor through this call; Rust duplicates it.
     */
public static func connectBroker(fd: Int32, generation: Data, control: BrokerControl, operationTimeoutMs: UInt64?)async throws  -> NativeDatabase  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_constructor_nativedatabase_connect_broker(FfiConverterInt32.lower(fd),FfiConverterData.lower(generation),FfiConverterCallbackInterfaceBrokerControl_lower(control),FfiConverterOptionUInt64.lower(operationTimeoutMs)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_u64,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_u64,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_u64,
            liftFunc: FfiConverterTypeNativeDatabase_lift,
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    

    
open func cancel()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_cancel(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func detach()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_detach(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func request() -> NativeRequest  {
    return try!  FfiConverterTypeNativeRequest_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_request(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func brokerBeginClose()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_broker_begin_close(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func brokerInterrupted()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_broker_interrupted(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func brokerIsUsable() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_broker_is_usable(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func brokerOperationBudget(remainingMs: UInt64?)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativedatabase_broker_operation_budget(
            self.uniffiCloneHandle(),
        FfiConverterOptionUInt64.lower(remainingMs),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeDatabase: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NativeDatabase

    public static func lift(_ handle: UInt64) throws -> NativeDatabase {
        return NativeDatabase(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NativeDatabase) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeDatabase {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NativeDatabase, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDatabase_lift(_ handle: UInt64) throws -> NativeDatabase {
    return try FfiConverterTypeNativeDatabase.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeDatabase_lower(_ value: NativeDatabase) -> UInt64 {
    return FfiConverterTypeNativeDatabase.lower(value)
}






public protocol NativeRequestProtocol: AnyObject, Sendable {
    
    func backup() async throws  -> Data
    
    func cancel() throws 
    
    func execute(bytes: Data) async throws  -> Data
    
    func stream(bytes: Data, sink: ChunkSink) async throws 
    
    func backupToFd(fd: Int32) async throws 
    
}
open class NativeRequest: NativeRequestProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_clone_nativerequest(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_oliphaunt_mobile_bindings_fn_free_nativerequest(handle, $0) }
    }

    

    
open func backup()async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativerequest_backup(
                        self.uniffiCloneHandle()
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_rust_buffer,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_rust_buffer,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func cancel()throws   {try rustCallWithError(FfiConverterTypeNativeError_lift) {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_method_nativerequest_cancel(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func execute(bytes: Data)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativerequest_execute(
                        self.uniffiCloneHandle(),FfiConverterData.lower(bytes)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_rust_buffer,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_rust_buffer,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func stream(bytes: Data, sink: ChunkSink)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativerequest_stream(
                        self.uniffiCloneHandle(),FfiConverterData.lower(bytes),FfiConverterCallbackInterfaceChunkSink_lower(sink)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    
open func backupToFd(fd: Int32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_method_nativerequest_backup_to_fd(
                        self.uniffiCloneHandle(),FfiConverterInt32.lower(fd)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeRequest: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NativeRequest

    public static func lift(_ handle: UInt64) throws -> NativeRequest {
        return NativeRequest(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NativeRequest) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeRequest {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NativeRequest, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeRequest_lift(_ handle: UInt64) throws -> NativeRequest {
    return try FfiConverterTypeNativeRequest.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeRequest_lower(_ value: NativeRequest) -> UInt64 {
    return FfiConverterTypeNativeRequest.lower(value)
}




public struct BrokerReady: Equatable, Hashable {
    public var generation: Data
    public var abi: UInt32
    public var runtimeVersion: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(generation: Data, abi: UInt32, runtimeVersion: String) {
        self.generation = generation
        self.abi = abi
        self.runtimeVersion = runtimeVersion
    }

    

    
}

#if compiler(>=6)
extension BrokerReady: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrokerReady: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrokerReady {
        return
            try BrokerReady(
                generation: FfiConverterData.read(from: &buf), 
                abi: FfiConverterUInt32.read(from: &buf), 
                runtimeVersion: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: BrokerReady, into buf: inout [UInt8]) {
        FfiConverterData.write(value.generation, into: &buf)
        FfiConverterUInt32.write(value.abi, into: &buf)
        FfiConverterString.write(value.runtimeVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerReady_lift(_ buf: RustBuffer) throws -> BrokerReady {
    return try FfiConverterTypeBrokerReady.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerReady_lower(_ value: BrokerReady) -> RustBuffer {
    return FfiConverterTypeBrokerReady.lower(value)
}


public struct OpenOptions: Equatable, Hashable {
    public var libraryPath: String?
    public var pgdata: String
    public var runtimeDirectory: String?
    public var moduleDirectory: String?
    public var icuDataDirectory: String?
    public var username: String
    public var database: String
    public var startupArgs: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(libraryPath: String?, pgdata: String, runtimeDirectory: String?, moduleDirectory: String?, icuDataDirectory: String?, username: String, database: String, startupArgs: [String]) {
        self.libraryPath = libraryPath
        self.pgdata = pgdata
        self.runtimeDirectory = runtimeDirectory
        self.moduleDirectory = moduleDirectory
        self.icuDataDirectory = icuDataDirectory
        self.username = username
        self.database = database
        self.startupArgs = startupArgs
    }

    

    
}

#if compiler(>=6)
extension OpenOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpenOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpenOptions {
        return
            try OpenOptions(
                libraryPath: FfiConverterOptionString.read(from: &buf), 
                pgdata: FfiConverterString.read(from: &buf), 
                runtimeDirectory: FfiConverterOptionString.read(from: &buf), 
                moduleDirectory: FfiConverterOptionString.read(from: &buf), 
                icuDataDirectory: FfiConverterOptionString.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                database: FfiConverterString.read(from: &buf), 
                startupArgs: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: OpenOptions, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.libraryPath, into: &buf)
        FfiConverterString.write(value.pgdata, into: &buf)
        FfiConverterOptionString.write(value.runtimeDirectory, into: &buf)
        FfiConverterOptionString.write(value.moduleDirectory, into: &buf)
        FfiConverterOptionString.write(value.icuDataDirectory, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterString.write(value.database, into: &buf)
        FfiConverterSequenceString.write(value.startupArgs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenOptions_lift(_ buf: RustBuffer) throws -> OpenOptions {
    return try FfiConverterTypeOpenOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenOptions_lower(_ value: OpenOptions) -> RustBuffer {
    return FfiConverterTypeOpenOptions.lower(value)
}



public enum BrokerExecution: Equatable, Hashable {
    
    case notStarted
    case completed
    case unknown





}

#if compiler(>=6)
extension BrokerExecution: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrokerExecution: FfiConverterRustBuffer {
    typealias SwiftType = BrokerExecution

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrokerExecution {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notStarted
        
        case 2: return .completed
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BrokerExecution, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notStarted:
            writeInt(&buf, Int32(1))
        
        
        case .completed:
            writeInt(&buf, Int32(2))
        
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerExecution_lift(_ buf: RustBuffer) throws -> BrokerExecution {
    return try FfiConverterTypeBrokerExecution.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerExecution_lower(_ value: BrokerExecution) -> RustBuffer {
    return FfiConverterTypeBrokerExecution.lower(value)
}




public enum BrokerReason: Equatable, Hashable {
    
    case invalidRequest
    case cancelled
    case deadline
    case workerInterrupted
    case transport
    case database
    case callback





}

#if compiler(>=6)
extension BrokerReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrokerReason: FfiConverterRustBuffer {
    typealias SwiftType = BrokerReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrokerReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .invalidRequest
        
        case 2: return .cancelled
        
        case 3: return .deadline
        
        case 4: return .workerInterrupted
        
        case 5: return .transport
        
        case 6: return .database
        
        case 7: return .callback
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BrokerReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .invalidRequest:
            writeInt(&buf, Int32(1))
        
        
        case .cancelled:
            writeInt(&buf, Int32(2))
        
        
        case .deadline:
            writeInt(&buf, Int32(3))
        
        
        case .workerInterrupted:
            writeInt(&buf, Int32(4))
        
        
        case .transport:
            writeInt(&buf, Int32(5))
        
        
        case .database:
            writeInt(&buf, Int32(6))
        
        
        case .callback:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerReason_lift(_ buf: RustBuffer) throws -> BrokerReason {
    return try FfiConverterTypeBrokerReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrokerReason_lower(_ value: BrokerReason) -> RustBuffer {
    return FfiConverterTypeBrokerReason.lower(value)
}



public 
enum NativeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NotSubmitted
    case Database(detail: String
    )
    case Callback
    case Broker(reason: BrokerReason, execution: BrokerExecution, requiresReopen: Bool, detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension NativeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeError: FfiConverterRustBuffer {
    typealias SwiftType = NativeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotSubmitted
        case 2: return .Database(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Callback
        case 4: return .Broker(
            reason: try FfiConverterTypeBrokerReason.read(from: &buf), 
            execution: try FfiConverterTypeBrokerExecution.read(from: &buf), 
            requiresReopen: try FfiConverterBool.read(from: &buf), 
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotSubmitted:
            writeInt(&buf, Int32(1))
        
        
        case let .Database(detail):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(detail, into: &buf)
            
        
        case .Callback:
            writeInt(&buf, Int32(3))
        
        
        case let .Broker(reason,execution,requiresReopen,detail):
            writeInt(&buf, Int32(4))
            FfiConverterTypeBrokerReason.write(reason, into: &buf)
            FfiConverterTypeBrokerExecution.write(execution, into: &buf)
            FfiConverterBool.write(requiresReopen, into: &buf)
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeError_lift(_ buf: RustBuffer) throws -> NativeError {
    return try FfiConverterTypeNativeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeError_lower(_ value: NativeError) -> RustBuffer {
    return FfiConverterTypeNativeError.lower(value)
}




public protocol BrokerControl: AnyObject, Sendable {
    
    func cancelRequest(epoch: Data, request: UInt64)  -> Bool
    
    func closeWorker(epoch: Data)  -> Bool
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceBrokerControl {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceBrokerControl = UniffiVTableCallbackInterfaceBrokerControl(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceBrokerControl.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface BrokerControl: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceBrokerControl.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface BrokerControl: handle missing in uniffiClone")
            }
        },
        cancelRequest: { (
            uniffiHandle: UInt64,
            epoch: RustBuffer,
            request: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrokerControl.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.cancelRequest(
                     epoch: try FfiConverterData.lift(epoch),
                     request: try FfiConverterUInt64.lift(request)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        closeWorker: { (
            uniffiHandle: UInt64,
            epoch: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrokerControl.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.closeWorker(
                     epoch: try FfiConverterData.lift(epoch)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceBrokerControl> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceBrokerControl>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitBrokerControl() {
    uniffi_oliphaunt_mobile_bindings_fn_init_callback_vtable_brokercontrol(UniffiCallbackInterfaceBrokerControl.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceBrokerControl {
    fileprivate static let handleMap = UniffiHandleMap<BrokerControl>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceBrokerControl : FfiConverter {
    typealias SwiftType = BrokerControl
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBrokerControl_lift(_ handle: UInt64) throws -> BrokerControl {
    return try FfiConverterCallbackInterfaceBrokerControl.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBrokerControl_lower(_ v: BrokerControl) -> UInt64 {
    return FfiConverterCallbackInterfaceBrokerControl.lower(v)
}




public protocol BrokerRetirement: AnyObject, Sendable {
    
    func retire() 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceBrokerRetirement {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceBrokerRetirement = UniffiVTableCallbackInterfaceBrokerRetirement(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceBrokerRetirement.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface BrokerRetirement: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceBrokerRetirement.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface BrokerRetirement: handle missing in uniffiClone")
            }
        },
        retire: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrokerRetirement.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.retire(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceBrokerRetirement> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceBrokerRetirement>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitBrokerRetirement() {
    uniffi_oliphaunt_mobile_bindings_fn_init_callback_vtable_brokerretirement(UniffiCallbackInterfaceBrokerRetirement.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceBrokerRetirement {
    fileprivate static let handleMap = UniffiHandleMap<BrokerRetirement>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceBrokerRetirement : FfiConverter {
    typealias SwiftType = BrokerRetirement
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBrokerRetirement_lift(_ handle: UInt64) throws -> BrokerRetirement {
    return try FfiConverterCallbackInterfaceBrokerRetirement.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBrokerRetirement_lower(_ v: BrokerRetirement) -> UInt64 {
    return FfiConverterCallbackInterfaceBrokerRetirement.lower(v)
}




public protocol ChunkSink: AnyObject, Sendable {
    
    func onChunk(bytes: Data)  -> Bool
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceChunkSink {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceChunkSink = UniffiVTableCallbackInterfaceChunkSink(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceChunkSink.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ChunkSink: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceChunkSink.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ChunkSink: handle missing in uniffiClone")
            }
        },
        onChunk: { (
            uniffiHandle: UInt64,
            bytes: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceChunkSink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onChunk(
                     bytes: try FfiConverterData.lift(bytes)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceChunkSink> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceChunkSink>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitChunkSink() {
    uniffi_oliphaunt_mobile_bindings_fn_init_callback_vtable_chunksink(UniffiCallbackInterfaceChunkSink.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceChunkSink {
    fileprivate static let handleMap = UniffiHandleMap<ChunkSink>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceChunkSink : FfiConverter {
    typealias SwiftType = ChunkSink
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceChunkSink_lift(_ handle: UInt64) throws -> ChunkSink {
    return try FfiConverterCallbackInterfaceChunkSink.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceChunkSink_lower(_ v: ChunkSink) -> UInt64 {
    return FfiConverterCallbackInterfaceChunkSink.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureOliphauntMobileBindingsInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func restore(libraryPath: String?, destination: String, bytes: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_func_restore(FfiConverterOptionString.lower(libraryPath),FfiConverterString.lower(destination),FfiConverterData.lower(bytes)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
public func brokerRestore(fd: Int32, generation: Data, control: BrokerControl, operationTimeoutMs: UInt64?, sourceFd: Int32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_oliphaunt_mobile_bindings_fn_func_broker_restore(FfiConverterInt32.lower(fd),FfiConverterData.lower(generation),FfiConverterCallbackInterfaceBrokerControl_lower(control),FfiConverterOptionUInt64.lower(operationTimeoutMs),FfiConverterInt32.lower(sourceFd)
                )
            },
            pollFunc: ffi_oliphaunt_mobile_bindings_rust_future_poll_void,
            completeFunc: ffi_oliphaunt_mobile_bindings_rust_future_complete_void,
            freeFunc: ffi_oliphaunt_mobile_bindings_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeNativeError_lift
        )
}
public func publishBackup(staging: String, destination: String)throws   {try rustCallWithError(FfiConverterTypeNativeError_lift) {
        uniffiCallStatus in
    uniffi_oliphaunt_mobile_bindings_fn_func_publish_backup(
        FfiConverterString.lower(staging),
        FfiConverterString.lower(destination),uniffiCallStatus
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_oliphaunt_mobile_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_func_restore() != 49609) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_func_broker_restore() != 21835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_func_publish_backup() != 28002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_cancel() != 46929) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_detach() != 36852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_request() != 20721) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_broker_begin_close() != 56799) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_broker_interrupted() != 1389) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_broker_is_usable() != 18385) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativedatabase_broker_operation_budget() != 17367) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativerequest_backup() != 18561) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativerequest_cancel() != 57008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativerequest_execute() != 57697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativerequest_stream() != 53216) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativerequest_backup_to_fd() != 48199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_cancel_request() != 22024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_close() != 9113) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_generation() != 34121) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_open() != 49703) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_restore() != 21954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_retire() != 51287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_nativebrokerworker_serve() != 30866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_constructor_nativedatabase_open() != 53366) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_constructor_nativedatabase_connect_broker() != 54329) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_constructor_nativebrokerworker_create() != 27260) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_chunksink_on_chunk() != 6719) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_brokercontrol_cancel_request() != 60789) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_brokercontrol_close_worker() != 50845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_oliphaunt_mobile_bindings_checksum_method_brokerretirement_retire() != 403) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitBrokerControl()
    uniffiCallbackInitBrokerRetirement()
    uniffiCallbackInitChunkSink()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOliphauntMobileBindingsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all